PathPecheurManager = {}

dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Models\\Path.lua")
dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Enums\\LogEnum.lua")

function PathPecheurManager:new()

    local object = {}
    setmetatable(object, self)
    self.__index = self
    return object
end

function PathPecheurManager:GatherAllPoisonAstrub()
    local path = {
        { map = "4,-19", path = "top", gather = false, fight = false },  
        { map = "4,-20", path = "top", gather = true, fight = false },  
        { map = "4,-21", path = "top", gather = false, fight = false },  
        { map = "4,-22", path = "right", gather = false, fight = false },  
        { map = "5,-22", path = "right", gather = false, fight = false },  
        { map = "6,-28", path = "left", gather = true, fight = false },  
        { map = "3,-30", path = "bottom", gather = true, fight = false },  
        { map = "5,-29", path = "top", gather = false, fight = false },  
        { map = "5,-30", path = "left", gather = false, fight = false },  
        { map = "3,-29", path = "bottom", gather = false, fight = false },  
        { map = "3,-25", path = "bottom", gather = false, fight = false },  
        { map = "3,-24", path = "bottom", gather = false, fight = false },  
        { map = "3,-23", path = "bottom", gather = false, fight = false },  
        { map = "3,-22", path = "bottom", gather = false, fight = false },  
        { map = "3,-21", path = "bottom", gather = false, fight = false },  
        { map = "3,-20", path = "left", gather = true, fight = false },  
        { map = "2,-20", path = "top", gather = true, fight = false },  
        { map = "2,-21", path = "left", gather = true, fight = false },  
        { map = "1,-21", path = "bottom", gather = true, fight = false },  
        { map = "1,-20", path = "bottom", gather = true, fight = false },  
        { map = "1,-19", path = "bottom", gather = false, fight = false },  
        { map = "1,-18", path = "bottom", gather = false, fight = false },  
        { map = "1,-17", path = "bottom", gather = false, fight = false },  
        { map = "1,-16", path = "bottom", gather = false, fight = false },  
        { map = "1,-15", path = "bottom", gather = false, fight = false },  
        { map = "1,-14", path = "right", gather = false, fight = false },  
        { map = "2,-14", path = "right", gather = false, fight = false },  
        { map = "3,-14", path = "bottom", gather = false, fight = false },  
        { map = "3,-13", path = "bottom", gather = false, fight = false },  
        { map = "3,-12", path = "bottom", gather = true, fight = false },  
        { map = "3,-11", path = "bottom", gather = false, fight = false },  
        { map = "3,-10", path = "left", gather = false, fight = false },  
        { map = "2,-10", path = "bottom", gather = false, fight = false },  
        { map = "2,-9", path = "bottom", gather = false, fight = false },  
        { map = "3,-8", path = "top", gather = true, fight = false },  
        { map = "5,-9", path = "right", gather = true, fight = false },  
        { map = "6,-9", path = "right", gather = true, fight = false },  
        { map = "7,-9", path = "right", gather = true, fight = false },  
        { map = "5,-14", path = "top", gather = false, fight = false },  
        { map = "5,-15", path = "top", gather = false, fight = false },  
        { map = "5,-16", path = "top", gather = false, fight = false },  
        { map = "5,-17", path = "top", gather = false, fight = false },  
        { map = "5,-18", path = "top", gather = false, fight = false },  
        { map = "5,-19", path = "left", gather = false, fight = false },  
        { map = "6,-19", path = "left", gather = false, fight = false },  
        { map = "6,-18", path = "left", gather = false, fight = false },  
        { map = "6,-17", path = "left", gather = false, fight = false },  
        { map = "191104002", path = "top", gather = false, fight = false },  
        { map = "192415750", path = "409" },  
        { map = "4,-17", path = "top", gather = false, fight = false },  
        { map = "3,-19", path = "right", gather = false, fight = false },  
        { map = "3,-18", path = "right", gather = false, fight = false },  
        { map = "3,-17", path = "right", gather = false, fight = false },  
        { map = "2,-18", path = "right", gather = false, fight = false },  
        { map = "2,-19", path = "bottom", gather = false, fight = false },  
        { map = "2,-17", path = "top", gather = false, fight = false },  
        { map = "2,-16", path = "top", gather = false, fight = false },  
        { map = "2,-15", path = "top", gather = false, fight = false },  
        { map = "3,-16", path = "right", gather = false, fight = false },  
        { map = "4,-16", path = "right", gather = false, fight = false },  
        { map = "4,-15", path = "right", gather = false, fight = false },  
        { map = "3,-15", path = "right", gather = false, fight = false },  
        { map = "6,-16", path = "left", gather = false, fight = false },  
        { map = "6,-15", path = "left", gather = false, fight = false },  
        { map = "7,-16", path = "left", gather = false, fight = false },  
        { map = "7,-15", path = "left", gather = false, fight = false },  
        { map = "7,-17", path = "top", gather = false, fight = false },  
        { map = "7,-18", path = "top", gather = false, fight = false },  
        { map = "7,-19", path = "top", gather = false, fight = false },  
        { map = "7,-20", path = "left", gather = false, fight = false },  
        { map = "7,-21", path = "left", gather = false, fight = false },  
        { map = "6,-21", path = "left", gather = false, fight = false },  
        { map = "6,-20", path = "left", gather = false, fight = false },  
        { map = "5,-20", path = "left", gather = false, fight = false },  
        { map = "5,-21", path = "left", gather = false, fight = false },  
        { map = "2,-8", path = "right", gather = true, fight = false },  
        { map = "3,-9", path = "right", gather = true, fight = false },  
        { map = "4,-9", path = "right", gather = true, fight = false },  
        { map = "8,-9", path = "bottom", gather = true, fight = false },  
        { map = "8,-8", path = "right", gather = true, fight = false },  
        { map = "9,-8", path = "top", gather = true, fight = false },  
        { map = "9,-9", path = "top", gather = true, fight = false },  
        { map = "9,-10", path = "right", gather = true, fight = false },  
        { map = "10,-10", path = "top", gather = true, fight = false },  
        { map = "10,-11", path = "right", gather = true, fight = false },  
        { map = "11,-11", path = "top", gather = true, fight = false },  
        { map = "11,-12", path = "top", gather = true, fight = false },  
        { map = "11,-13", path = "top", gather = true, fight = false },  
        { map = "11,-14", path = "left", gather = true, fight = false },  
        { map = "10,-14", path = "bottom", gather = true, fight = false },  
        { map = "8,-14", path = "bottom", gather = true, fight = false },  
        { map = "10,-13", path = "left", gather = true, fight = false },  
        { map = "9,-14", path = "left", gather = true, fight = false },  
        { map = "8,-13", path = "left", gather = true, fight = false },  
        { map = "7,-14", path = "left", gather = true, fight = false },  
        { map = "6,-14", path = "bottom", gather = true, fight = false },  
        { map = "9,-13", path = "top", gather = true, fight = false },  
        { map = "7,-13", path = "top", gather = true, fight = false },  
        { map = "6,-13", path = "bottom", gather = true, fight = false },  
        { map = "6,-12", path = "right", gather = false, fight = false },  
        { map = "7,-12", path = "right", gather = false, fight = false },  
        { map = "8,-12", path = "bottom", gather = false, fight = false },  
        { map = "8,-11", path = "bottom", gather = true, fight = false },  
        { map = "8,-10", path = "left", gather = true, fight = false },  
        { map = "7,-10", path = "left", gather = true, fight = false },  
        { map = "6,-10", path = "left", gather = true, fight = false },  
        { map = "5,-10", path = "top", gather = true, fight = false },  
        { map = "5,-11", path = "top", gather = true, fight = false },  
        { map = "5,-12", path = "top", gather = false, fight = false },  
        { map = "5,-13", path = "top", gather = false, fight = false },  
        { map = "5,-28", path = "top", gather = true, fight = false },  
        { map = "3,-28", path = "bottom", gather = true, fight = false },  
        { map = "6,-22", path = "right", gather = true, fight = false },  
        { map = "7,-22", path = "right", gather = true, fight = false },  
        { map = "8,-22", path = "right", gather = false, fight = false },  
        { map = "9,-22", path = "bottom", gather = false, fight = false },  
        { map = "9,-21", path = "right", gather = false, fight = false },  
        { map = "10,-21", path = "right", gather = false, fight = false },  
        { map = "11,-21", path = "top", gather = false, fight = false },  
        { map = "11,-22", path = "right", gather = false, fight = false },  
        { map = "12,-22", path = "top", gather = true, fight = false },  
        { map = "12,-23", path = "top", gather = true, fight = false },  
        { map = "12,-24", path = "top", gather = true, fight = false },  
        { map = "12,-25", path = "top", gather = true, fight = false },  
        { map = "12,-26", path = "top", gather = true, fight = false },  
        { map = "12,-27", path = "right", gather = true, fight = false },  
        { map = "13,-27", path = "top", gather = true, fight = false },  
        { map = "13,-28", path = "left", gather = true, fight = false },  
        { map = "12,-28", path = "left", gather = true, fight = false },  
        { map = "11,-28", path = "left", gather = true, fight = false },  
        { map = "10,-28", path = "top", gather = true, fight = false },  
        { map = "10,-29", path = "left", gather = true, fight = false },  
        { map = "9,-29", path = "left", gather = true, fight = false },  
        { map = "8,-29", path = "bottom", gather = true, fight = false },  
        { map = "8,-28", path = "left", gather = true, fight = false },  
        { map = "7,-28", path = "bottom", gather = true, fight = false },  
        { map = "7,-27", path = "bottom", gather = true, fight = false },  
        { map = "7,-26", path = "bottom", gather = true, fight = false },  
        { map = "7,-25", path = "bottom", gather = true, fight = false },  
        { map = "7,-24", path = "bottom", gather = true, fight = false },  
        { map = "7,-23", path = "left", gather = true, fight = false },  
        { map = "6,-23", path = "left", gather = true, fight = false },  
        { map = "5,-23", path = "top", gather = true, fight = false },  
        { map = "5,-24", path = "right", gather = true, fight = false },  
        { map = "6,-24", path = "top", gather = true, fight = false },  
        { map = "6,-25", path = "left", gather = true, fight = false },  
        { map = "5,-25", path = "top", gather = true, fight = false },  
        { map = "5,-26", path = "right", gather = true, fight = false },  
        { map = "6,-26", path = "top", gather = true, fight = false },  
        { map = "6,-27", path = "top", gather = true, fight = false },  
        { map = "3,-27", path = "bottom", gather = true, fight = false },  
        { map = "3,-26", path = "bottom", gather = true, fight = false },  
        { map = "4,-30", path = "top", gather = true, fight = false },  
        { map = "4,-31", path = "left", gather = true, fight = false },  
        { map = "3,-31", path = "bottom", gather = true, fight = false },  
   }

    return Path:new(path, "GatherAllPoisonAstrub", true)
end

function PathPecheurManager:GatherGoujonAstrub()
    local path = {
        { map = "4,-19", path = "top", gather = false, fight = false },  
        { map = "4,-20", path = "top", gather = true, fight = false },  
        { map = "4,-21", path = "top", gather = false, fight = false },  
        { map = "4,-22", path = "right", gather = false, fight = false },  
        { map = "5,-22", path = "right", gather = false, fight = false },  
        { map = "6,-22", path = "top", gather = true, fight = false },  
        { map = "6,-23", path = "right", gather = true, fight = false },  
        { map = "6,-24", path = "left", gather = true, fight = false },  
        { map = "5,-25", path = "right", gather = false, fight = false },  
        { map = "6,-25", path = "right", gather = true, fight = false },  
        { map = "7,-25", path = "top", gather = true, fight = false },  
        { map = "5,-24", path = "top", gather = true, fight = false },  
        { map = "7,-24", path = "left", gather = false, fight = false },  
        { map = "7,-23", path = "top", gather = true, fight = false },  
        { map = "7,-26", path = "top", gather = false, fight = false },  
        { map = "7,-27", path = "top", gather = false, fight = false },  
        { map = "7,-28", path = "left", gather = false, fight = false },  
        { map = "6,-28", path = "left", gather = true, fight = false },  
        { map = "4,-30", path = "left", gather = true, fight = false },  
        { map = "3,-30", path = "bottom", gather = true, fight = false },  
        { map = "5,-29", path = "top", gather = false, fight = false },  
        { map = "5,-28", path = "top", gather = false, fight = false },  
        { map = "5,-30", path = "left", gather = false, fight = false },  
        { map = "3,-29", path = "bottom", gather = false, fight = false },  
        { map = "3,-28", path = "bottom", gather = false, fight = false },  
        { map = "3,-27", path = "bottom", gather = false, fight = false },  
        { map = "3,-26", path = "bottom", gather = false, fight = false },  
        { map = "3,-25", path = "bottom", gather = false, fight = false },  
        { map = "3,-24", path = "bottom", gather = false, fight = false },  
        { map = "3,-23", path = "bottom", gather = false, fight = false },  
        { map = "3,-22", path = "bottom", gather = false, fight = false },  
        { map = "3,-21", path = "bottom", gather = false, fight = false },  
        { map = "3,-20", path = "left", gather = true, fight = false },  
        { map = "2,-20", path = "top", gather = true, fight = false },  
        { map = "2,-21", path = "left", gather = true, fight = false },  
        { map = "1,-21", path = "bottom", gather = true, fight = false },  
        { map = "1,-20", path = "bottom", gather = true, fight = false },  
        { map = "1,-19", path = "bottom", gather = false, fight = false },  
        { map = "1,-18", path = "bottom", gather = false, fight = false },  
        { map = "1,-17", path = "bottom", gather = false, fight = false },  
        { map = "1,-16", path = "bottom", gather = false, fight = false },  
        { map = "1,-15", path = "bottom", gather = false, fight = false },  
        { map = "1,-14", path = "right", gather = false, fight = false },  
        { map = "2,-14", path = "right", gather = false, fight = false },  
        { map = "3,-14", path = "bottom", gather = false, fight = false },  
        { map = "3,-13", path = "bottom", gather = false, fight = false },  
        { map = "3,-12", path = "bottom", gather = true, fight = false },  
        { map = "3,-11", path = "bottom", gather = false, fight = false },  
        { map = "3,-10", path = "left", gather = false, fight = false },  
        { map = "2,-10", path = "bottom", gather = false, fight = false },  
        { map = "2,-9", path = "bottom", gather = false, fight = false },  
        { map = "2,-8", path = "right", gather = false, fight = false },  
        { map = "3,-8", path = "top", gather = true, fight = false },  
        { map = "3,-9", path = "right", gather = false, fight = false },  
        { map = "4,-9", path = "right", gather = false, fight = false },  
        { map = "5,-9", path = "right", gather = true, fight = false },  
        { map = "6,-9", path = "right", gather = true, fight = false },  
        { map = "7,-9", path = "right", gather = true, fight = false },  
        { map = "8,-9", path = "top", gather = true, fight = false },  
        { map = "8,-10", path = "top", gather = true, fight = false },  
        { map = "8,-11", path = "left", gather = false, fight = false },  
        { map = "7,-11", path = "left", gather = false, fight = false },  
        { map = "6,-11", path = "left", gather = false, fight = false },  
        { map = "5,-11", path = "top", gather = true, fight = false },  
        { map = "5,-12", path = "top", gather = false, fight = false },  
        { map = "5,-13", path = "right", gather = false, fight = false },  
        { map = "6,-13", path = "right", gather = true, fight = false },  
        { map = "7,-13", path = "right", gather = true, fight = false },  
        { map = "8,-13", path = "right", gather = true, fight = false },  
        { map = "9,-13", path = "right", gather = true, fight = false },  
        { map = "10,-13", path = "top", gather = true, fight = false },  
        { map = "10,-14", path = "left", gather = false, fight = false },  
        { map = "9,-14", path = "left", gather = false, fight = false },  
        { map = "8,-14", path = "left", gather = true, fight = false },  
        { map = "7,-14", path = "left", gather = true, fight = false },  
        { map = "6,-14", path = "left", gather = false, fight = false },  
        { map = "5,-14", path = "top", gather = false, fight = false },  
        { map = "5,-15", path = "top", gather = false, fight = false },  
        { map = "5,-16", path = "top", gather = false, fight = false },  
        { map = "5,-17", path = "top", gather = false, fight = false },  
        { map = "5,-18", path = "top", gather = false, fight = false },  
        { map = "5,-19", path = "left", gather = false, fight = false },  
        { map = "6,-19", path = "left", gather = false, fight = false },  
        { map = "6,-18", path = "left", gather = false, fight = false },  
        { map = "6,-17", path = "left", gather = false, fight = false },  
        { map = "191104002", path = "top", gather = false, fight = false },  
        { map = "192415750", path = "409" },  
        { map = "4,-17", path = "top", gather = false, fight = false },  
        { map = "3,-19", path = "right", gather = false, fight = false },  
        { map = "3,-18", path = "right", gather = false, fight = false },  
        { map = "3,-17", path = "right", gather = false, fight = false },  
        { map = "2,-18", path = "right", gather = false, fight = false },  
        { map = "2,-19", path = "bottom", gather = false, fight = false },  
        { map = "2,-17", path = "top", gather = false, fight = false },  
        { map = "2,-16", path = "top", gather = false, fight = false },  
        { map = "2,-15", path = "top", gather = false, fight = false },  
        { map = "3,-16", path = "right", gather = false, fight = false },  
        { map = "4,-16", path = "right", gather = false, fight = false },  
        { map = "4,-15", path = "right", gather = false, fight = false },  
        { map = "3,-15", path = "right", gather = false, fight = false },  
        { map = "6,-16", path = "left", gather = false, fight = false },  
        { map = "6,-15", path = "left", gather = false, fight = false },  
        { map = "7,-16", path = "left", gather = false, fight = false },  
        { map = "7,-15", path = "left", gather = false, fight = false },  
        { map = "7,-17", path = "top", gather = false, fight = false },  
        { map = "7,-18", path = "top", gather = false, fight = false },  
        { map = "7,-19", path = "top", gather = false, fight = false },  
        { map = "7,-20", path = "left", gather = false, fight = false },  
        { map = "7,-21", path = "left", gather = false, fight = false },  
        { map = "6,-21", path = "left", gather = false, fight = false },  
        { map = "6,-20", path = "left", gather = false, fight = false },  
        { map = "5,-20", path = "left", gather = false, fight = false },  
        { map = "5,-21", path = "left", gather = false, fight = false },  
    }

    return Path:new(path, "GatherGoujonAstrub", true)
end

function PathPecheurManager:AtelierPecheurAstrub()
    map:moveToward(192937984)
end