PathBucheronManager = {}

dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Models\\Path.lua")
dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Enums\\LogEnum.lua")

function PathBucheronManager:new()

    local object = {}
    setmetatable(object, self)
    self.__index = self
    return object
end

function PathBucheronManager:GatherBoisAstrub()
	local path = {
		{map = "192415750", path="409"},
		{map = "4,-18", path="top"},
        {map = "5,-18", path = "top"}, --map zaap astrub
        {map = "5,-19", path = "left"}, --map zaap astrub
		{map = "-2,-20", path = "right"},
		{map = "4,-21", path = "bottom", gather = true},
		{map = "4,-20", path = "bottom", gather = true},
		{map = "6,-21", path = "left", gather = true},
		{map = "5,-21", path = "left", gather = true},
		{map = "6,-20", path = "top"},
		{map = "4,-19", path = "left"},
		{map = "3,-19", path = "bottom", gather = true},
		{map = "3,-18", path = "bottom"},
		{map = "3,-17", path = "right"},
		{map = "17,-21", path = "right"},
		{map = "4,-17", path = "right", gather = true},
		{map = "5,-17", path = "bottom", gather = true},
		{map = "5,-16", path = "right", gather = true},
		{map = "6,-16", path = "bottom"},
		{map = "6,-15", path = "right", gather = true},
		{map = "7,-15", path = "right", gather = true},
		{map = "8,-15", path = "bottom"},
		{map = "8,-14", path = "right", gather = true},
		{map = "9,-14", path = "right", gather = true},
		{map = "10,-14", path = "bottom", gather = true},
		{map = "10,-13", path = "bottom", gather = true},
		{map = "10,-12", path = "bottom"},
		{map = "10,-11", path = "bottom"},
		{map = "10,-10", path = "left", gather = true},
		{map = "9,-11", path = "left", gather = true},
		{map = "9,-10", path = "top"},
		{map = "8,-11", path = "top", gather = true},
		{map = "8,-12", path = "top", gather = true},
		{map = "8,-13", path = "left"},
		{map = "7,-13", path = "left", gather = true},
		{map = "6,-13", path = "bottom", gather = true},
		{map = "6,-12", path = "bottom", gather = true},
		{map = "6,-11", path = "left", gather = true},
		{map = "5,-11", path = "top"},
		{map = "5,-12", path = "top", gather = true},
		{map = "5,-13", path = "left", gather = true},
		{map = "4,-10", path = "left", gather = true},
		{map = "4,-13", path = "bottom", gather = true},
		{map = "4,-12", path = "bottom", gather = true},
		{map = "4,-11", path = "bottom", gather = true},
		{map = "3,-10", path = "top", gather = true},
		{map = "2,-11", path = "top", gather = true},
		{map = "3,-11", path = "left", gather = true},
		{map = "2,-12", path = "top"},
		{map = "2,-13", path = "top"},
		{map = "2,-14", path = "top", gather = true},
		{map = "2,-15", path = "right", gather = true},
		{map = "4,-15", path = "top", gather = true},
		{map = "3,-15", path = "right", gather = true},
		{map = "4,-16", path = "left"},
		{map = "3,-16", path = "left"},
		{map = "2,-16", path = "top", gather = true},
		{map = "2,-17", path = "left", gather = true},
		{map = "1,-17", path = "bottom"},
		{map = "1,-16", path = "bottom", gather = true},
		{map = "1,-15", path = "bottom"},
		{map = "1,-14", path = "left", gather = true},
		{map = "0,-14", path = "top"},
		{map = "0,-15", path = "left", gather = true},
		{map = "-1,-15", path = "left", gather = true},
		{map = "-2,-15", path = "left", gather = true},
		{map = "0,-17", path = "left", gather = true},
		{map = "-1,-17", path = "left", gather = true},
		{map = "-2,-17", path = "left", gather = true},
		{map = "-3,-17", path = "top", gather = true},
		{map = "-3,-15", path = "top", gather = true},
		{map = "-3,-16", path = "right", gather = true},
		{map = "-2,-16", path = "right", gather = true},
		{map = "-1,-16", path = "right", gather = true},
		{map = "-2,-18", path = "right", gather = true},
		{map = "-3,-18", path = "right", gather = true},
		{map = "-1,-18", path = "right", gather = true},
		{map = "0,-18", path = "right", gather = true},
		{map = "0,-16", path = "top", gather = true},
		{map = "1,-18", path = "top", gather = true},
		{map = "1,-19", path = "left", gather = true},
		{map = "0,-19", path = "left", gather = true},
		{map = "-1,-19", path = "left", gather = true},
		{map = "-2,-19", path = "left", gather = true},
		{map = "-3,-19", path = "top", gather = true},
		{map = "-3,-20", path = "right", gather = true},
		{map = "-1,-20", path = "right", gather = true},
		{map = "0,-20", path = "right", gather = true},
		{map = "1,-20", path = "right", gather = true},
		{map = "2,-20", path = "top", gather = true},
		{map = "2,-21", path = "left", gather = true},
		{map = "1,-21", path = "left"},
		{map = "0,-21", path = "left", gather = true},
		{map = "-1,-21", path = "left", gather = true},
		{map = "-2,-21", path = "left", gather = true},
		{map = "-3,-21", path = "top", gather = true},
		{map = "-3,-22", path = "right", gather = true},
		{map = "-2,-22", path = "right", gather = true},
		{map = "-1,-22", path = "right", gather = true},
		{map = "1,-22", path = "right", gather = true},
		{map = "2,-22", path = "top", gather = true},
		{map = "0,-22", path = "right", gather = true},
		{map = "2,-23", path = "left", gather = true},
		{map = "1,-23", path = "left", gather = true},
		{map = "0,-23", path = "left", gather = true},
		{map = "-1,-23", path = "left", gather = true},
		{map = "-2,-23", path = "top", gather = true},
		{map = "-2,-24", path = "right", gather = true},
		{map = "-1,-24", path = "right", gather = true},
		{map = "0,-24", path = "right", gather = true},
		{map = "1,-24", path = "right", gather = true},
		{map = "2,-24", path = "top", gather = true},
		{map = "2,-25", path = "left", gather = true},
		{map = "1,-25", path = "left", gather = true},
		{map = "0,-25", path = "left", gather = true},
		{map = "-1,-25", path = "left", gather = true},
		{map = "-2,-25", path = "top", gather = true},
		{map = "-2,-26", path = "right", gather = true},
		{map = "-1,-26", path = "right", gather = true},
		{map = "0,-26", path = "right", gather = true},
		{map = "1,-26", path = "right", gather = true},
		{map = "2,-26", path = "top", gather = true},
		{map = "1,-27", path = "left", gather = true},
		{map = "2,-27", path = "left", gather = true},
		{map = "0,-27", path = "left", gather = true},
		{map = "-1,-27", path = "left", gather = true},
		{map = "-2,-27", path = "top", gather = true},
		{map = "-2,-28", path = "right", gather = true},
		{map = "-1,-28", path = "right", gather = true},
		{map = "1,-28", path = "right", gather = true},
		{map = "0,-28", path = "right", gather = true},
		{map = "2,-28", path = "top", gather = true},
		{map = "2,-29", path = "top", gather = true},
		{map = "2,-30", path = "right", gather = true},
		{map = "3,-30", path = "bottom"},
		{map = "3,-29", path = "bottom"},
		{map = "3,-28", path = "bottom"},
		{map = "3,-27", path = "bottom"},
		{map = "3,-25", path = "bottom"},
		{map = "3,-26", path = "bottom"},
		{map = "3,-24", path = "bottom"},
		{map = "3,-23", path = "bottom"},
		{map = "3,-22", path = "right"},
		{map = "4,-22", path = "right"},
		{map = "5,-22", path = "bottom"},
	}
	
    return Path:new(path, "GatherBoisAstrub", true)
end

function PathBucheronManager:AtelierBucheronAstrub()
    map:moveToward(192940042)
end