FightPathManager = {}

function FightPathManager:new()
    dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Models\\Path.lua")

    local object = {}
    setmetatable(object, self)
    self.__index = self
    return object
end

function FightPathManager:FarmRouteDesAmes()
    return {
        {map = "4,-1", path = "bottom"},
        {map = "5,-1", path = "left"},
        {map = "4,0", path = "left"},
        {map = "5,0", path = "left"},
        {map = "4,1", path = "top"},
        {map = "3,1", path = "top"},
        {map = "3,0", path = "top"},
        {map = "3,-2", path = "top"},
        {map = "3,-1", path = "top"},
        {map = "2,0", path = "top"},
        {map = "2,-1", path = "top"},
        {map = "2,-2", path = "top"},
        {map = "1,-2", path = "top"},
        {map = "0,-2", path = "top"},
        {map = "0,-1", path = "top"},
        {map = "1,-1", path = "top"},
        {map = "1,0", path = "top"},
        {map = "0,1", path = "top"},
        {map = "-1,1", path = "top"},
        {map = "-1,0", path = "left"},
        {map = "-2,0", path = "top"},
        {map = "-1,-2", path = "top"},
        {map = "-1,-1", path = "top"},
        {map = "-2,-1", path = "top"},
        {map = "-2,-2", path = "top"},
        {map = "-3,-5", path = "right"},
        {map = "-3,-6", path = "right"},
        {map = "-2,-6", path = "bottom"},
        {map = "-2,-5", path = "bottom"},
        {map = "-1,-6", path = "bottom"},
        {map = "-1,-5", path = "bottom"},
        {map = "0,-5", path = "bottom"},
        {map = "1,-5", path = "bottom"},
        {map = "2,-5", path = "bottom"},
        {map = "3,-5", path = "bottom"},
        {map = "4,-4", path = "bottom"},
        {map = "3,-4", path = "bottom"},
        {map = "2,-4", path = "bottom"},
        {map = "-2,-4", path = "bottom"},
        {map = "-1,-4", path = "bottom"},
        {map = "0,-4", path = "bottom"},
        {map = "1,-4", path = "bottom"},
        {map = "152044547", path = "right"},
        {map = "152043521", path = "right"},
        {map = "152045573", path = "right"},
        {map = "152046593", path = "right"},
        {map = "152043523", path = "right"},
        {map = "152046599", path = "right"},
        {map = "152044553", path = "right"},
        {map = "152046595", path = "right"},
        {map = "152044545", path = "right"},
        {map = "152045575", path = "right"},
        {map = "152045571", path = "right"},
        {map = "152043529", path = "right"},
        {map = "152043527", path = "right"},
        {map = "152043525", path = "right"},
        {map = "152045569", path = "right"},
        {map = "152046597", path = "right"},
        {map = "152044549", path = "right"},
        {map = "153092354", door = "409"},
        -- Cartes de combats
        {map = "-1,-3", path = "left|right", fight = true},
        {map = "-2,-3", path = "right", fight = true},
        {map = "3,-3", path = "left", fight = true},
        {map = "0,-3", path = "left|right", fight = true},
        {map = "1,-3", path = "left|right", fight = true},
        {map = "2,-3", path = "left|right", fight = true},
    }
end

function FightPathManager:FarmChampsIncarnam()
    return {
        {map = "-1,-2", path = "top"},
        {map = "-2,-2", path = "top"},
        {map = "-2,-3", path = "top"},
        {map = "3,-3", path = "left"},
        {map = "5,-1", path = "bottom"},
        {map = "4,-1", path = "bottom"},
        {map = "3,1", path = "top"},
        {map = "3,0", path = "top"},
        {map = "2,0", path = "top"},
        {map = "1,0", path = "top"},
        {map = "0,-1", path = "right"},
        {map = "0,1", path = "top"},
        {map = "-1,1", path = "top"},
        {map = "-1,0", path = "top"},
        {map = "-2,0", path = "top"},
        {map = "-2,-1", path = "top"},
        {map = "-1,-1", path = "top"},
        {map = "4,-3", path = "left"},
        {map = "4,-4", path = "left"},
        {map = "2,-4", path = "bottom"},
        {map = "3,-4", path = "bottom"},
        {map = "5,0", path = "left"},
        {map = "4,0", path = "left"},
        {map = "4,1", path = "top"},
        {map = "1,-1", path = "top"},
        {map = "2,-1", path = "top"},
        {map = "3,-5", path = "bottom"},
        {map = "2,-5", path = "bottom"},
        {map = "1,-5", path = "bottom"},
        {map = "1,-4", path = "bottom"},
        {map = "3,-1", path = "top"},
        {map = "3,-2", path = "top"},
        {map = "2,-2", path = "top"},
        {map = "1,-2", path = "top"},
        {map = "0,-2", path = "top"},
        {map = "2,-3", path = "left"},
        {map = "1,-3", path = "left"},
        {map = "0,-3", path = "left"},
        {map = "-1,-3", path = "top"},
        -- Cartes de combats
        {map = "-3,-6", path = "bottom", fight = true},
        {map = "-1,-6", path = "left", fight = true},
        {map = "-1,-5", path = "top|left", fight = true},
        {map = "0,-5", path = "left", fight = true},
        {map = "-2,-6", path = "left|bottom", fight = true},
        {map = "-2,-5", path = "bottom", fight = true},
        {map = "-2,-4", path = "right", fight = true},
        {map = "-3,-5", path = "right", fight = true},
        {map = "0,-4", path = "top", fight = true},
        {map = "-1,-4", path = "top|right", fight = true}
    }
end

function FightPathManager:FarmLacIncarnam()
    return {
        {map = "-1,-4", path = "bottom"},
        {map = "-1,-3", path = "bottom"},
        {map = "0,0", path = "right"},
        {map = "1,-4", path = "bottom"},
        {map = "1,-5", path = "bottom"},
        {map = "0,-3", path = "left"},
        {map = "1,-3", path = "left"},
        {map = "2,-3", path = "left"},
        {map = "3,-3", path = "left"},
        {map = "-2,-3", path = "bottom"},
        {map = "1,-2", path = "left"},
        {map = "1,-1", path = "top"},
        {map = "-3,-6", path = "right"},
        {map = "-2,-6", path = "right"},
        {map = "-3,-5", path = "right"},
        {map = "4,-1", path = "bottom"},
        {map = "5,0", path = "left"},
        {map = "5,-1", path = "left"},
        {map = "4,1", path = "left"},
        {map = "4,0", path = "left"},
        {map = "3,1", path = "top"},
        {map = "3,0", path = "top"},
        {map = "3,-2", path = "top"},
        {map = "3,-1", path = "top"},
        {map = "1,0", path = "top"},
        {map = "2,0", path = "top"},
        {map = "2,-2", path = "top"},
        {map = "2,-1", path = "top"},
        {map = "4,-3", path = "left"},
        {map = "4,-4", path = "bottom"},
        {map = "3,-4", path = "bottom"},
        {map = "3,-5", path = "bottom"},
        {map = "2,-5", path = "bottom"},
        {map = "2,-4", path = "bottom"},
        {map = "-2,-5", path = "right"},
        {map = "-2,-4", path = "right"},
        {map = "0,-4", path = "left"},
        {map = "0,-5", path = "left"},
        {map = "-1,-6", path = "bottom"},
        {map = "-1,-5", path = "bottom"},
        -- Cartes de combats
        {map = "-2,0", path = "right", fight = true},
        {map = "-2,-1", path = "right|bottom", fight = true},
        {map = "-2,-2", path = "bottom", fight = true},
        {map = "-1,-2", path = "left|right|bottom", fight = true},
        {map = "-1,-1", path = "top|left", fight = true},
        {map = "0,-1", path = "right", fight = true},
        {map = "0,1", path = "top", fight = true},
        {map = "-1,1", path = "right", fight = true},
        {map = "-1,0", path = "top|right|bottom", fight = true},
        {map = "0,-2", path = "left", fight = true},
    }
end

function FightPathManager:FarmForetIncarnam()
    return {
        {map = "5,0", path = "left"},
        {map = "4,0", path = "left"},
        {map = "4,1", path = "left"},
        {map = "3,0", path = "top"},
        {map = "3,1", path = "top"},
        {map = "-1,-6", path = "bottom"},
        {map = "-2,-6", path = "right"},
        {map = "-2,-5", path = "right"},
        {map = "-2,-4", path = "right"},
        {map = "-3,-6", path = "right"},
        {map = "-3,-5", path = "right"},
        {map = "0,1", path = "top"},
        {map = "3,-3", path = "left"},
        {map = "3,-4", path = "bottom"},
        {map = "3,-5", path = "bottom"},
        {map = "2,-5", path = "bottom"},
        {map = "2,-3", path = "bottom"},
        {map = "2,-4", path = "bottom"},
        {map = "1,-4", path = "bottom"},
        {map = "1,-5", path = "bottom"},
        {map = "0,-4", path = "bottom"},
        {map = "0,-5", path = "bottom"},
        {map = "-1,-4", path = "bottom"},
        {map = "-1,-5", path = "bottom"},
        {map = "-1,1", path = "top"},
        {map = "-1,0", path = "right"},
        {map = "-2,0", path = "right"},
        {map = "5,-1", path = "bottom"},
        {map = "4,-1", path = "bottom"},
        {map = "-2,-1", path = "top"},
        {map = "-1,-1", path = "top"},
        {map = "-2,-2", path = "top"},
        {map = "-1,-2", path = "top"},
        {map = "0,-2", path = "right"},
        {map = "-2,-3", path = "right"},
        {map = "-1,-3", path = "right"},
        {map = "0,-3", path = "right"},
        {map = "1,-3", path = "bottom"},
        {map = "0,-1", path = "bottom"},
        {map = "0,0", path = "right"},
        -- Cartes de combats
        {map = "2,0", path = "top", fight = true},
        {map = "1,0", path = "right", fight = true},
        {map = "1,-1", path = "bottom", fight = true},
        {map = "2,-2", path = "right|bottom", fight = true},
        {map = "1,-2", path = "right", fight = true},
        {map = "3,-1", path = "top", fight = true},
        {map = "2,-1", path = "right", fight = true},
        {map = "3,-2", path = "left", fight = true},
    }
end

function FightPathManager:FarmPaturageIncarnam()
    return {
        {map = "3,-1", path = "left"},
        {map = "2,-3", path = "top"},
        {map = "0,0", path = "right"},
        {map = "0,-3", path = "right"},
        {map = "-1,-3", path = "right"},
        {map = "-2,-3", path = "right"},
        {map = "1,0", path = "top"},
        {map = "1,-1", path = "top"},
        {map = "2,0", path = "top"},
        {map = "3,-3", path = "top"},
        {map = "4,1", path = "top"},
        {map = "3,1", path = "top"},
        {map = "3,0", path = "top"},
        {map = "0,1", path = "top"},
        {map = "-1,1", path = "top"},
        {map = "-1,-1", path = "top"},
        {map = "-2,-1", path = "top"},
        {map = "-1,0", path = "right"},
        {map = "5,-1", path = "bottom"},
        {map = "4,-1", path = "bottom"},
        {map = "4,0", path = "left"},
        {map = "5,0", path = "left"},
        {map = "-3,-5", path = "right"},
        {map = "-3,-6", path = "right"},
        {map = "-2,-6", path = "bottom"},
        {map = "-1,-6", path = "bottom"},
        {map = "0,-5", path = "right"},
        {map = "-1,-5", path = "right"},
        {map = "-2,-5", path = "right"},
        {map = "0,-4", path = "right"},
        {map = "-1,-4", path = "right"},
        {map = "-2,-4", path = "right"},
        {map = "-2,0", path = "right"},
        {map = "0,-2", path = "right"},
        {map = "-1,-2", path = "right"},
        {map = "-2,-2", path = "right"},
        {map = "1,-3", path = "right"},
        {map = "2,-1", path = "top"},
        {map = "2,-2", path = "top"},
        {map = "3,-2", path = "left"},
        {map = "1,-2", path = "right"},
        -- Cartes de combats
        {map = "1,-4", path = "right", fight = true},
        {map = "1,-5", path = "bottom", fight = true},
        {map = "2,-5", path = "left", fight = true},
        {map = "3,-5", path = "left", fight = true},
        {map = "2,-4", path = "top|right", fight = true},
        {map = "3,-4", path = "top", fight = true},
    }
end

function FightPathManager:FarmCimetiereIncarnam()
    return {
        {map = "-1,-4", path = "right"},
        {map = "3,-2", path = "left"},
        {map = "2,0", path = "top"},
        {map = "1,-2", path = "top"},
        {map = "1,-1", path = "top"},
        {map = "1,0", path = "top"},
        {map = "-1,-6", path = "bottom"},
        {map = "-2,-6", path = "bottom"},
        {map = "-3,-6", path = "bottom"},
        {map = "-3,-5", path = "right"},
        {map = "0,-5", path = "right"},
        {map = "-1,-5", path = "right"},
        {map = "-2,-5", path = "right"},
        {map = "0,-4", path = "right"},
        {map = "3,-4", path = "left"},
        {map = "-2,-4", path = "right"},
        {map = "0,-3", path = "right"},
        {map = "-1,-3", path = "right"},
        {map = "-2,-3", path = "right"},
        {map = "1,-3", path = "right"},
        {map = "1,-4", path = "right"},
        {map = "1,-5", path = "right"},
        {map = "2,-5", path = "bottom"},
        {map = "3,-5", path = "left"},
        {map = "-2,-2", path = "top"},
        {map = "-1,-2", path = "top"},
        {map = "-1,-1", path = "top"},
        {map = "-2,-1", path = "top"},
        {map = "0,1", path = "top"},
        {map = "-1,1", path = "top"},
        {map = "-2,0", path = "right"},
        {map = "-1,0", path = "right"},
        {map = "3,-3", path = "left"},
        {map = "2,-4", path = "bottom"},
        {map = "2,-3", path = "bottom"},
        {map = "2,-2", path = "bottom"},
        {map = "4,-4", path = "left"},
        {map = "4,-3", path = "left"},
        {map = "2,-1", path = "right"},
        {map = "3,-1", path = "bottom"},
        {map = "0,0", path = "right"},
        -- Cartes de combats
        {map = "3,1", path = "right", fight = true},
        {map = "4,0", path = "left|right", fight = true},
        {map = "4,-1", path = "bottom", fight = true},
        {map = "4,1", path = "top", fight = true},
        {map = "5,-1", path = "left", fight = true},
        {map = "3,0", path = "bottom", fight = true},
        {map = "5,0", path = "top", fight = true},
    }
end

function FightPathManager:FarmPiouAstrub()
    return{
        {map = "191889665", path = "388"},
        -- map astrub
        { map = "192415750", path = "409" },
        { map = "191104002", path = "top" },
        { map = "192416776", path = "bottom(550)", done = false },
        { map = "191106048", path = "bottom", fight = true },
        { map = "5,-19", path = "left", fight = true },
        { map = "4,-19", path = "left", fight = true },
        { map = "3,-19", path = "bottom", fight = true },
        { map = "3,-18", path = "left|bottom|right", fight = true },
        { map = "3,-17", path = "top", fight = true },
        { map = "4,-17", path = "left", fight = true },
        { map = "5,-17", path = "bottom|left", fight = true },
        { map = "5,-18", path = "right", fight = true },
        { map = "6,-17", path = "left", fight = true },
        { map = "6,-18", path = "bottom", fight = true },
        { map = "5,-18", path = "left", fight = true },
        { map = "7,-17", path = "top", fight = true },
        { map = "7,-18", path = "top", fight = true },
        { map = "7,-19", path = "top", fight = true },
        { map = "7,-20", path = "top", fight = true },
        { map = "7,-21", path = "left", fight = true },
        { map = "6,-21", path = "bottom", fight = true },
        { map = "6,-20", path = "left", fight = true },
        { map = "5,-20", path = "top", fight = true },
        { map = "5,-21", path = "left", fight = true },
        { map = "4,-21", path = "bottom", fight = true },
        { map = "3,-21", path = "left", fight = true },
        { map = "2,-21", path = "bottom|left", fight = true },
        { map = "1,-21", path = "bottom", fight = true },
        { map = "1,-20", path = "bottom", fight = true },
        { map = "2,-20", path = "left", fight = true },
        { map = "3,-20", path = "top", fight = true },
        { map = "4,-20", path = "left", fight = true },
        { map = "1,-20", path = "bottom", fight = true },
        { map = "1,-19", path = "right", fight = true },
        { map = "2,-19", path = "bottom", fight = true },
        { map = "1,-18", path = "bottom", fight = true },
        { map = "2,-18", path = "left", fight = true },
        { map = "1,-17", path = "right", fight = true },
        { map = "2,-17", path = "bottom", fight = true },
        { map = "1,-16", path = "bottom", fight = true },
        { map = "2,-16", path = "left", fight = true },
        { map = "2,-15", path = "right", fight = true },
        { map = "1,-15", path = "right", fight = true },
        { map = "3,-16", path = "right", fight = true },
        { map = "3,-15", path = "right", fight = true },
        { map = "4,-16", path = "right", fight = true },
        { map = "4,-15", path = "right", fight = true },
        { map = "5,-16", path = "right", fight = true },
        { map = "5,-15", path = "right", fight = true },
        { map = "6,-16", path = "right", fight = true },
        { map = "6,-15", path = "right", fight = true },
        { map = "7,-16", path = "top", fight = true },
        { map = "7,-15", path = "top", fight = true },
    }
end