GatherPathManager = {}

function GatherPathManager:new()
    dofile("C:\\ANKABOT\\Ankabot_Perso\\Domain\\Models\\Path.lua")

    local object = {}
    setmetatable(object, self)
    self.__index = self
    return object
end

function GatherPathManager:GatherOrtieAstrub()
    return {
        {map = "5,-18", path = "top", gather = false, fight = false},
        {map = "5,-19", path = "left", gather = false, fight = false},
        {map = "4,-19", path = "left", gather = true, fight = false},
        {map = "3,-19", path = "bottom", gather = true, fight = false},
        {map = "3,-18", path = "bottom", gather = false, fight = false},
        {map = "3,-17", path = "right", gather = false, fight = false},
        {map = "4,-17", path = "right", gather = false, fight = false},
        {map = "5,-17", path = "right", gather = true, fight = false},
        {map = "6,-17", path = "top", gather = true, fight = false},
        {map = "6,-18", path = "right", gather = false, fight = false},
        {map = "7,-18", path = "bottom", gather = false, fight = false},
        {map = "7,-17", path = "bottom", gather = false, fight = false},
        {map = "7,-16", path = "left", gather = true, fight = false},
        {map = "6,-16", path = "left", gather = true, fight = false},
        {map = "5,-16", path = "left", gather = false, fight = false},
        {map = "4,-16", path = "left", gather = false, fight = false},
        {map = "3,-16", path = "left", gather = true, fight = false},
        {map = "2,-16", path = "left", gather = true, fight = false},
        {map = "1,-16", path = "bottom", gather = true, fight = false},
        {map = "1,-15", path = "right", gather = true, fight = false},
        {map = "2,-15", path = "bottom", gather = true, fight = false},
        {map = "2,-14", path = "bottom", gather = false, fight = false},
        {map = "2,-13", path = "bottom", gather = false, fight = false},
        {map = "2,-12", path = "right", gather = false, fight = false},
        {map = "3,-14", path = "right", gather = true, fight = false},
        {map = "3,-12", path = "right", gather = true, fight = false},
        {map = "4,-13", path = "left", gather = true, fight = false},
        {map = "4,-14", path = "top", gather = true, fight = false},
        {map = "4,-12", path = "top", gather = true, fight = false},
        {map = "3,-13", path = "top", gather = true, fight = false},
        {map = "4,-15", path = "right", gather = true, fight = false},
        {map = "5,-15", path = "bottom", gather = false, fight = false},
        {map = "5,-14", path = "right", gather = true, fight = false},
        {map = "6,-14", path = "bottom", gather = true, fight = false},
        {map = "5,-13", path = "bottom", gather = true, fight = false},
        {map = "6,-13", path = "left", gather = true, fight = false},
        {map = "5,-12", path = "bottom", gather = true, fight = false},
        {map = "5,-11", path = "right", gather = true, fight = false},
        {map = "6,-11", path = "right", gather = true, fight = false},
        {map = "7,-11", path = "right", gather = true, fight = false},
        {map = "8,-11", path = "top", gather = true, fight = false},
        {map = "8,-12", path = "top", gather = true, fight = false},
        {map = "8,-13", path = "top", gather = true, fight = false},
        {map = "8,-14", path = "right", gather = false, fight = false},
        {map = "9,-14", path = "right", gather = true, fight = false},
        {map = "10,-14", path = "right", gather = false, fight = false},
        {map = "11,-14", path = "bottom", gather = false, fight = false},
        {map = "11,-13", path = "bottom", gather = false, fight = false},
        {map = "11,-12", path = "left", gather = true, fight = false},
        {map = "10,-12", path = "top", gather = false, fight = false},
        {map = "10,-13", path = "left", gather = true, fight = false},
        {map = "9,-13", path = "bottom", gather = true, fight = false},
        {map = "9,-12", path = "bottom", gather = true, fight = false},
        {map = "9,-11", path = "bottom", gather = true, fight = false},
        {map = "9,-10", path = "bottom", gather = true, fight = false},
        {map = "9,-9", path = "left", gather = false, fight = false},
        {map = "8,-9", path = "top", gather = true, fight = false},
        {map = "8,-10", path = "left", gather = true, fight = false},
        {map = "7,-10", path = "left", gather = true, fight = false},
        {map = "6,-10", path = "bottom", gather = true, fight = false},
        {map = "6,-9", path = "left", gather = true, fight = false},
        {map = "5,-9", path = "top", gather = true, fight = false},
        {map = "5,-10", path = "left", gather = true, fight = false},
        {map = "4,-10", path = "left", gather = true, fight = false},
        {map = "3,-10", path = "bottom", gather = true, fight = false},
        {map = "3,-9", path = "bottom", gather = true, fight = false},
        {map = "3,-8", path = "left", gather = true, fight = false},
        {map = "2,-8", path = "top", gather = false, fight = false},
        {map = "2,-9", path = "top", gather = false, fight = false},
        {map = "2,-10", path = "left", gather = false, fight = false},
        {map = "1,-10", path = "top", gather = false, fight = false},
        {map = "1,-11", path = "top", gather = false, fight = false},
        {map = "1,-12", path = "top", gather = false, fight = false},
        {map = "1,-13", path = "top", gather = false, fight = false},
        {map = "1,-14", path = "left", gather = false, fight = false},
        {map = "0,-14", path = "top", gather = false, fight = false},
        {map = "0,-15", path = "top", gather = false, fight = false},
        {map = "0,-16", path = "top", gather = false, fight = false},
        {map = "0,-17", path = "right", gather = false, fight = false},
        {map = "1,-17", path = "right", gather = false, fight = false},
        {map = "2,-17", path = "top", gather = true, fight = false},
        {map = "2,-18", path = "left", gather = false, fight = false},
        {map = "1,-18", path = "top", gather = false, fight = false},
        {map = "1,-19", path = "top", gather = true, fight = false},
        {map = "1,-20", path = "right", gather = false, fight = false},
        {map = "2,-20", path = "right", gather = false, fight = false},
        {map = "3,-20", path = "right", gather = true, fight = false},
        {map = "4,-20", path = "right", gather = false, fight = false},
        {map = "5,-20", path = "right", gather = true, fight = false},
        {map = "6,-20", path = "right", gather = false, fight = false},
        {map = "7,-20", path = "top", gather = true, fight = false},
        {map = "7,-21", path = "left", gather = false, fight = false},
        {map = "6,-21", path = "left", gather = true, fight = false},
        {map = "5,-21", path = "left", gather = false, fight = false},
        {map = "4,-21", path = "left", gather = false, fight = false},
        {map = "3,-21", path = "left", gather = false, fight = false},
        {map = "2,-21", path = "top", gather = true, fight = false},
        {map = "1,-22", path = "top", gather = true, fight = false},
        {map = "2,-23", path = "top", gather = true, fight = false},
        {map = "2,-22", path = "left", gather = true, fight = false},
        {map = "1,-23", path = "right", gather = true, fight = false},
        {map = "2,-24", path = "right", gather = true, fight = false},
        {map = "3,-24", path = "top", gather = false, fight = false},
        {map = "3,-25", path = "left", gather = true, fight = false},
        {map = "2,-25", path = "top", gather = true, fight = false},
        {map = "2,-26", path = "top", gather = true, fight = false},
        {map = "2,-27", path = "top", gather = true, fight = false},
        {map = "2,-28", path = "top", gather = true, fight = false},
        {map = "2,-29", path = "top", gather = true, fight = false},
        {map = "2,-30", path = "right", gather = true, fight = false},
        {map = "3,-30", path = "top", gather = true, fight = false},
        {map = "3,-31", path = "right", gather = true, fight = false},
        {map = "4,-31", path = "bottom", gather = true, fight = false},
        {map = "4,-30", path = "bottom", gather = true, fight = false},
        {map = "4,-29", path = "left", gather = true, fight = false},
        {map = "3,-29", path = "bottom", gather = true, fight = false},
        {map = "3,-28", path = "right", gather = true, fight = false},
        {map = "4,-28", path = "bottom", gather = true, fight = false},
        {map = "4,-27", path = "bottom", gather = true, fight = false},
        {map = "4,-26", path = "right", gather = true, fight = false},
        {map = "5,-26", path = "top", gather = false, fight = false},
        {map = "5,-27", path = "top", gather = false, fight = false},
        {map = "5,-28", path = "top", gather = false, fight = false},
        {map = "5,-29", path = "top", gather = true, fight = false},
        {map = "6,-29", path = "bottom", gather = true, fight = false},
        {map = "5,-30", path = "right", gather = true, fight = false},
        {map = "6,-30", path = "bottom", gather = true, fight = false},
        {map = "6,-28", path = "bottom", gather = true, fight = false},
        {map = "6,-27", path = "bottom", gather = false, fight = false},
        {map = "6,-26", path = "right", gather = true, fight = false},
        {map = "7,-26", path = "bottom", gather = false, fight = false},
        {map = "7,-25", path = "bottom", gather = true, fight = false},
        {map = "7,-24", path = "right", gather = false, fight = false},
        {map = "8,-24", path = "right", gather = false, fight = false},
        {map = "9,-24", path = "bottom", gather = false, fight = false},
        {map = "9,-23", path = "left", gather = true, fight = false},
        {map = "8,-23", path = "left", gather = false, fight = false},
        {map = "7,-23", path = "bottom", gather = false, fight = false},
        {map = "7,-22", path = "right", gather = true, fight = false},
        {map = "8,-22", path = "bottom", gather = false, fight = false},
        {map = "8,-21", path = "bottom", gather = false, fight = false},
        {map = "8,-20", path = "bottom", gather = false, fight = false},
        {map = "8,-19", path = "bottom", gather = false, fight = false},
        {map = "8,-18", path = "left", gather = false, fight = false},
    }
end

function GatherPathManager:GatherOrtieAndSaugeAstrub()
    return {
        {map = "5,-18", path = "top", gather = false, fight = false},
        {map = "5,-19", path = "left", gather = false, fight = false},
        {map = "4,-19", path = "left", gather = true, fight = false},
        {map = "3,-19", path = "bottom", gather = true, fight = false},
        {map = "3,-18", path = "bottom", gather = false, fight = false},
        {map = "3,-17", path = "right", gather = false, fight = false},
        {map = "4,-17", path = "right", gather = false, fight = false},
        {map = "5,-17", path = "right", gather = true, fight = false},
        {map = "6,-17", path = "top", gather = true, fight = false},
        {map = "6,-18", path = "right", gather = false, fight = false},
        {map = "7,-18", path = "bottom", gather = false, fight = false},
        {map = "7,-17", path = "bottom", gather = false, fight = false},
        {map = "7,-16", path = "left", gather = true, fight = false},
        {map = "6,-16", path = "left", gather = true, fight = false},
        {map = "5,-16", path = "left", gather = false, fight = false},
        {map = "4,-16", path = "left", gather = false, fight = false},
        {map = "3,-16", path = "left", gather = true, fight = false},
        {map = "2,-16", path = "left", gather = true, fight = false},
        {map = "1,-16", path = "bottom", gather = true, fight = false},
        {map = "1,-15", path = "right", gather = true, fight = false},
        {map = "2,-15", path = "bottom", gather = true, fight = false},
        {map = "2,-14", path = "bottom", gather = false, fight = false},
        {map = "2,-13", path = "bottom", gather = false, fight = false},
        {map = "2,-12", path = "right", gather = false, fight = false},
        {map = "3,-14", path = "right", gather = true, fight = false},
        {map = "3,-12", path = "right", gather = true, fight = false},
        {map = "4,-13", path = "left", gather = true, fight = false},
        {map = "4,-14", path = "top", gather = true, fight = false},
        {map = "4,-12", path = "top", gather = true, fight = false},
        {map = "3,-13", path = "top", gather = true, fight = false},
        {map = "4,-15", path = "right", gather = true, fight = false},
        {map = "5,-15", path = "bottom", gather = false, fight = false},
        {map = "5,-14", path = "right", gather = true, fight = false},
        {map = "5,-13", path = "bottom", gather = true, fight = false},
        {map = "6,-13", path = "left", gather = true, fight = false},
        {map = "5,-12", path = "bottom", gather = true, fight = false},
        {map = "5,-11", path = "right", gather = true, fight = false},
        {map = "6,-11", path = "right", gather = true, fight = false},
        {map = "7,-11", path = "right", gather = true, fight = false},
        {map = "8,-11", path = "top", gather = true, fight = false},
        {map = "8,-12", path = "top", gather = true, fight = false},
        {map = "8,-13", path = "top", gather = true, fight = false},
        {map = "8,-14", path = "right", gather = false, fight = false},
        {map = "9,-14", path = "right", gather = true, fight = false},
        {map = "10,-14", path = "right", gather = false, fight = false},
        {map = "11,-14", path = "bottom", gather = false, fight = false},
        {map = "11,-13", path = "bottom", gather = false, fight = false},
        {map = "11,-12", path = "left", gather = true, fight = false},
        {map = "10,-12", path = "top", gather = false, fight = false},
        {map = "10,-13", path = "left", gather = true, fight = false},
        {map = "9,-13", path = "bottom", gather = true, fight = false},
        {map = "9,-12", path = "bottom", gather = true, fight = false},
        {map = "9,-11", path = "bottom", gather = true, fight = false},
        {map = "9,-10", path = "bottom", gather = true, fight = false},
        {map = "9,-9", path = "left", gather = false, fight = false},
        {map = "8,-9", path = "top", gather = true, fight = false},
        {map = "8,-10", path = "left", gather = true, fight = false},
        {map = "7,-10", path = "left", gather = true, fight = false},
        {map = "6,-10", path = "bottom", gather = true, fight = false},
        {map = "6,-9", path = "left", gather = true, fight = false},
        {map = "5,-9", path = "top", gather = true, fight = false},
        {map = "5,-10", path = "left", gather = true, fight = false},
        {map = "3,-10", path = "bottom", gather = true, fight = false},
        {map = "3,-9", path = "bottom", gather = true, fight = false},
        {map = "3,-8", path = "left", gather = true, fight = false},
        {map = "2,-8", path = "top", gather = false, fight = false},
        {map = "2,-9", path = "top", gather = false, fight = false},
        {map = "2,-10", path = "left", gather = false, fight = false},
        {map = "1,-10", path = "top", gather = false, fight = false},
        {map = "1,-11", path = "top", gather = false, fight = false},
        {map = "1,-12", path = "top", gather = false, fight = false},
        {map = "1,-13", path = "top", gather = false, fight = false},
        {map = "1,-14", path = "left", gather = false, fight = false},
        {map = "0,-14", path = "top", gather = false, fight = false},
        {map = "0,-15", path = "top", gather = false, fight = false},
        {map = "0,-16", path = "top", gather = false, fight = false},
        {map = "0,-17", path = "right", gather = false, fight = false},
        {map = "1,-17", path = "right", gather = false, fight = false},
        {map = "2,-17", path = "top", gather = true, fight = false},
        {map = "1,-19", path = "top", gather = true, fight = false},
        {map = "1,-20", path = "right", gather = false, fight = false},
        {map = "2,-20", path = "right", gather = false, fight = false},
        {map = "3,-20", path = "right", gather = true, fight = false},
        {map = "4,-20", path = "right", gather = false, fight = false},
        {map = "5,-20", path = "right", gather = true, fight = false},
        {map = "6,-20", path = "right", gather = false, fight = false},
        {map = "7,-20", path = "top", gather = true, fight = false},
        {map = "7,-21", path = "left", gather = false, fight = false},
        {map = "5,-21", path = "left", gather = false, fight = false},
        {map = "4,-21", path = "left", gather = false, fight = false},
        {map = "3,-21", path = "left", gather = false, fight = false},
        {map = "2,-21", path = "top", gather = true, fight = false},
        {map = "2,-23", path = "top", gather = true, fight = false},
        {map = "2,-22", path = "left", gather = true, fight = false},
        {map = "1,-23", path = "right", gather = true, fight = false},
        {map = "2,-24", path = "right", gather = true, fight = false},
        {map = "3,-24", path = "top", gather = false, fight = false},
        {map = "3,-25", path = "left", gather = true, fight = false},
        {map = "2,-25", path = "top", gather = true, fight = false},
        {map = "2,-26", path = "top", gather = true, fight = false},
        {map = "2,-27", path = "top", gather = true, fight = false},
        {map = "2,-28", path = "top", gather = true, fight = false},
        {map = "2,-29", path = "top", gather = true, fight = false},
        {map = "2,-30", path = "right", gather = true, fight = false},
        {map = "3,-30", path = "top", gather = true, fight = false},
        {map = "4,-31", path = "bottom", gather = true, fight = false},
        {map = "4,-30", path = "bottom", gather = true, fight = false},
        {map = "4,-29", path = "left", gather = true, fight = false},
        {map = "3,-29", path = "bottom", gather = true, fight = false},
        {map = "3,-28", path = "right", gather = true, fight = false},
        {map = "4,-28", path = "bottom", gather = true, fight = false},
        {map = "4,-27", path = "bottom", gather = true, fight = false},
        {map = "4,-26", path = "right", gather = true, fight = false},
        {map = "5,-26", path = "top", gather = false, fight = false},
        {map = "5,-27", path = "top", gather = false, fight = false},
        {map = "5,-28", path = "top", gather = false, fight = false},
        {map = "5,-29", path = "top", gather = true, fight = false},
        {map = "6,-29", path = "bottom", gather = true, fight = false},
        {map = "5,-30", path = "right", gather = true, fight = false},
        {map = "6,-30", path = "bottom", gather = true, fight = false},
        {map = "6,-27", path = "bottom", gather = false, fight = false},
        {map = "6,-26", path = "right", gather = true, fight = false},
        {map = "7,-26", path = "bottom", gather = false, fight = false},
        {map = "7,-24", path = "right", gather = false, fight = false},
        {map = "8,-24", path = "right", gather = false, fight = false},
        {map = "9,-24", path = "bottom", gather = false, fight = false},
        {map = "9,-23", path = "left", gather = true, fight = false},
        {map = "8,-23", path = "left", gather = false, fight = false},
        {map = "7,-23", path = "bottom", gather = false, fight = false},
        {map = "7,-22", path = "right", gather = true, fight = false},
        {map = "8,-22", path = "bottom", gather = false, fight = false},
        {map = "8,-21", path = "bottom", gather = false, fight = false},
        {map = "8,-20", path = "bottom", gather = false, fight = false},
        {map = "8,-19", path = "bottom", gather = false, fight = false},
        {map = "8,-18", path = "left", gather = false, fight = false},
        {map = "2,-18", path = "top", gather = false, fight = false},
        {map = "2,-19", path = "left", gather = true, fight = false},
        {map = "6,-21", path = "top", gather = true, fight = false},
        {map = "6,-22", path = "left", gather = false, fight = false},
        {map = "5,-22", path = "bottom", gather = true, fight = false},
        {map = "7,-28", path = "bottom", gather = true, fight = false},
        {map = "7,-27", path = "left", gather = false, fight = false},
        {map = "6,-28", path = "right", gather = true, fight = false},
        {map = "5,-25", path = "bottom", gather = false, fight = false},
        {map = "5,-24", path = "right", gather = false, fight = false},
        {map = "6,-24", path = "right", gather = true, fight = false},
        {map = "7,-25", path = "left", gather = true, fight = false},
        {map = "6,-25", path = "left", gather = false, fight = false},
        {map = "4,-10", path = "top", gather = true, fight = false},
        {map = "4,-11", path = "left", gather = false, fight = false},
        {map = "3,-11", path = "bottom", gather = true, fight = false},
        {map = "6,-14", path = "top", gather = false, fight = false},
        {map = "6,-15", path = "right", gather = false, fight = false},
        {map = "7,-15", path = "bottom", gather = true, fight = false},
        {map = "7,-14", path = "bottom", gather = true, fight = false},
        {map = "7,-13", path = "bottom", gather = true, fight = false},
        {map = "7,-12", path = "left", gather = true, fight = false},
        {map = "6,-12", path = "top", gather = true, fight = false},
        {map = "1,-22", path = "left", gather = false, fight = false},
        {map = "0,-22", path = "left", gather = false, fight = false},
        {map = "-1,-22", path = "bottom", gather = false, fight = false},
        {map = "-1,-21", path = "left", gather = false, fight = false},
        {map = "-2,-21", path = "top", gather = true, fight = false},
        {map = "-2,-22", path = "top", gather = true, fight = false},
        {map = "-2,-23", path = "top", gather = true, fight = false},
        {map = "1,-28", path = "bottom", gather = true, fight = false},
        {map = "1,-27", path = "bottom", gather = true, fight = false},
        {map = "1,-26", path = "bottom", gather = true, fight = false},
        {map = "1,-25", path = "bottom", gather = true, fight = false},
        {map = "1,-24", path = "bottom", gather = true, fight = false},
        {map = "-2,-24", path = "top", gather = true, fight = false},
        {map = "-2,-27", path = "right", gather = true, fight = false},
        {map = "-1,-24", path = "right", gather = true, fight = false},
        {map = "-2,-25", path = "top", gather = false, fight = false},
        {map = "-2,-26", path = "top", gather = false, fight = false},
        {map = "-1,-25", path = "bottom", gather = false, fight = false},
        {map = "0,-25", path = "top", gather = false, fight = false},
        {map = "0,-24", path = "top", gather = true, fight = false},
        {map = "0,-26", path = "top", gather = true, fight = false},
        {map = "0,-27", path = "top", gather = true, fight = false},
        {map = "0,-28", path = "right", gather = true, fight = false},
        {map = "-1,-27", path = "bottom", gather = true, fight = false},
        {map = "-1,-26", path = "bottom", gather = true, fight = false},
        {map = "3,-31", path = "top", gather = true, fight = false},
        {map = "3,-32", path = "right", gather = true, fight = false},
        {map = "4,-32", path = "bottom", gather = true, fight = false},
    }
end

function GatherPathManager:GatherAllAstrubNorthEast()
    local path = {
        {map = "5,-19", path = "left", gather = false, fight = false},
        { map = "3,-19", path = "bottom", gather = true, fight = false },  
        { map = "3,-18", path = "left", gather = true, fight = false },  
        { map = "2,-18", path = "bottom", gather = true, fight = false },  
        { map = "2,-17", path = "bottom", gather = true, fight = false },  
        { map = "2,-16", path = "bottom", gather = true, fight = false },  
        { map = "2,-15", path = "bottom", gather = true, fight = false },  
        { map = "2,-14", path = "left", gather = true, fight = false },  
        { map = "1,-14", path = "top", gather = true, fight = false },  
        { map = "1,-15", path = "left", gather = true, fight = false },  
        { map = "0,-15", path = "left", gather = true, fight = false },  
        { map = "-1,-15", path = "left", gather = true, fight = false },  
        { map = "-2,-15", path = "left", gather = true, fight = false },  
        { map = "-3,-15", path = "top", gather = true, fight = false },  
        { map = "-3,-16", path = "right", gather = true, fight = false },  
        { map = "-2,-16", path = "right", gather = true, fight = false },  
        { map = "-1,-16", path = "right", gather = true, fight = false },  
        { map = "0,-16", path = "right", gather = true, fight = false },  
        { map = "1,-16", path = "top", gather = true, fight = false },  
        { map = "1,-17", path = "left", gather = true, fight = false },  
        { map = "0,-17", path = "left", gather = true, fight = false },  
        { map = "-1,-17", path = "left", gather = true, fight = false },  
        { map = "-2,-17", path = "left", gather = true, fight = false },  
        { map = "-3,-17", path = "top", gather = true, fight = false },  
        { map = "-3,-18", path = "right", gather = true, fight = false },  
        { map = "-2,-18", path = "right", gather = true, fight = false },  
        { map = "-1,-18", path = "right", gather = true, fight = false },  
        { map = "0,-18", path = "right", gather = true, fight = false },  
        { map = "1,-18", path = "top", gather = true, fight = false },  
        { map = "1,-19", path = "right", gather = true, fight = false },  
        { map = "2,-19", path = "top", gather = true, fight = false },  
        { map = "2,-20", path = "left", gather = true, fight = false },  
        { map = "1,-20", path = "left", gather = true, fight = false },  
        { map = "0,-20", path = "bottom", gather = true, fight = false },  
        { map = "0,-19", path = "left", gather = true, fight = false },  
        { map = "-1,-19", path = "left", gather = true, fight = false },  
        { map = "-2,-19", path = "left", gather = true, fight = false },  
        { map = "-3,-19", path = "top", gather = true, fight = false },  
        { map = "-3,-20", path = "right", gather = true, fight = false },  
        { map = "-2,-20", path = "right", gather = true, fight = false },  
        { map = "-1,-20", path = "top", gather = true, fight = false },  
        { map = "-1,-21", path = "right|left|top", gather = true, fight = false },  
        { map = "0,-21", path = "right", gather = true, fight = false },  
        { map = "-2,-21", path = "left", gather = true, fight = false },  
        { map = "-3,-21", path = "top", gather = true, fight = false },  
        { map = "-3,-22", path = "right", gather = true, fight = false },  
        { map = "-2,-22", path = "right", gather = true, fight = false },  
        { map = "-1,-22", path = "right", gather = true, fight = false },  
        { map = "0,-22", path = "right", gather = true, fight = false },  
        { map = "1,-21", path = "top", gather = true, fight = false },  
        { map = "1,-22", path = "top", gather = true, fight = false },  
        { map = "1,-23", path = "left", gather = true, fight = false },  
        { map = "0,-23", path = "left", gather = true, fight = false },  
        { map = "-1,-23", path = "left", gather = true, fight = false },  
        { map = "-2,-23", path = "left", gather = true, fight = false },  
        { map = "-3,-23", path = "top", gather = true, fight = false },  
        { map = "-3,-24", path = "right", gather = true, fight = false },  
        { map = "-2,-24", path = "right", gather = true, fight = false },  
        { map = "-1,-24", path = "right", gather = true, fight = false },  
        { map = "0,-24", path = "right", gather = true, fight = false },  
        { map = "1,-24", path = "top", gather = true, fight = false },  
        { map = "1,-25", path = "left", gather = true, fight = false },  
        { map = "0,-25", path = "left", gather = true, fight = false },  
        { map = "-2,-25", path = "left", gather = true, fight = false },  
        { map = "-1,-25", path = "left", gather = true, fight = false },  
        { map = "-3,-25", path = "top", gather = true, fight = false },  
        { map = "-3,-26", path = "right", gather = true, fight = false },  
        { map = "-2,-26", path = "right", gather = true, fight = false },  
        { map = "-1,-26", path = "right", gather = true, fight = false },  
        { map = "0,-26", path = "right", gather = true, fight = false },  
        { map = "1,-26", path = "top", gather = true, fight = false },  
        { map = "1,-27", path = "left", gather = true, fight = false },  
        { map = "0,-27", path = "left", gather = true, fight = false },  
        { map = "-1,-27", path = "left", gather = true, fight = false },  
        { map = "-2,-27", path = "left", gather = true, fight = false },  
        { map = "-3,-27", path = "top", gather = true, fight = false },  
        { map = "-3,-28", path = "right|top", gather = true, fight = false },  
        { map = "-2,-28", path = "right", gather = true, fight = false },  
        { map = "-1,-28", path = "right", gather = true, fight = false },  
        { map = "0,-28", path = "right", gather = true, fight = false },  
        { map = "1,-28", path = "right", gather = true, fight = false },  
        { map = "2,-28", path = "right", gather = true, fight = false },  
        { map = "-3,-29", path = "right", gather = true, fight = false },  
        { map = "-2,-29", path = "top", gather = true, fight = false },  
        { map = "-2,-30", path = "right", gather = false, fight = false },  
        { map = "-1,-30", path = "top", gather = false, fight = false },  
        { map = "-1,-31", path = "top", gather = true, fight = false },  
        { map = "-1,-32", path = "right|top", gather = true, fight = false },  
        { map = "-1,-33", path = "right", gather = true, fight = false },  
        { map = "0,-32", path = "top", gather = true, fight = false },  
        { map = "0,-33", path = "top", gather = true, fight = false },  
        { map = "0,-34", path = "right", gather = true, fight = false },  
        { map = "1,-34", path = "right", gather = true, fight = false },  
        { map = "2,-34", path = "bottom", gather = true, fight = false },  
        { map = "3,-33", path = "bottom", gather = true, fight = false },  
        { map = "2,-33", path = "right|bottom", gather = true, fight = false },  
        { map = "2,-32", path = "right", gather = true, fight = false },  
        { map = "3,-32", path = "right", gather = true, fight = false },  
        { map = "4,-32", path = "bottom", gather = true, fight = false },  
        { map = "4,-31", path = "right|left", gather = true, fight = false },  
        { map = "5,-31", path = "bottom", gather = true, fight = false },  
        { map = "3,-31", path = "bottom", gather = true, fight = false },  
        { map = "3,-30", path = "left", gather = true, fight = false },  
        { map = "2,-30", path = "bottom", gather = true, fight = false },  
        { map = "2,-29", path = "bottom", gather = true, fight = false },  
        { map = "5,-30", path = "right|left", gather = true, fight = false },  
        { map = "4,-30", path = "left", gather = true, fight = false },  
        { map = "6,-30", path = "bottom", gather = true, fight = false },  
        { map = "6,-29", path = "left", gather = true, fight = false },  
        { map = "5,-29", path = "left", gather = true, fight = false },  
        { map = "4,-29", path = "left", gather = true, fight = false },  
        { map = "3,-29", path = "left|bottom", gather = true, fight = false },  
        { map = "3,-28", path = "right", gather = true, fight = false },  
        { map = "4,-28", path = "right", gather = true, fight = false },  
        { map = "5,-28", path = "right", gather = true, fight = false },  
        { map = "6,-28", path = "right", gather = true, fight = false },  
        { map = "7,-28", path = "bottom", gather = true, fight = false },  
        { map = "7,-27", path = "left", gather = true, fight = false },  
        { map = "6,-27", path = "left", gather = true, fight = false },  
        { map = "5,-27", path = "left", gather = true, fight = false },  
        { map = "4,-27", path = "left", gather = true, fight = false },  
        { map = "2,-27", path = "bottom", gather = true, fight = false },  
        { map = "2,-26", path = "right", gather = true, fight = false },  
        { map = "3,-26", path = "right", gather = true, fight = false },  
        { map = "4,-26", path = "right", gather = true, fight = false },  
        { map = "5,-26", path = "right", gather = true, fight = false },  
        { map = "6,-26", path = "right", gather = true, fight = false },  
        { map = "7,-26", path = "bottom", gather = true, fight = false },  
        { map = "7,-25", path = "left", gather = true, fight = false },  
        { map = "6,-25", path = "left", gather = true, fight = false },  
        { map = "5,-25", path = "left", gather = true, fight = false },  
        { map = "4,-25", path = "left", gather = false, fight = false },  
        { map = "3,-25", path = "left", gather = true, fight = false },  
        { map = "2,-25", path = "bottom", gather = true, fight = false },  
        { map = "3,-27", path = "left", gather = false, fight = false },  
        { map = "2,-24", path = "right", gather = true, fight = false },  
        { map = "3,-24", path = "right", gather = true, fight = false },  
        { map = "4,-24", path = "right", gather = true, fight = false },  
        { map = "5,-24", path = "right", gather = true, fight = false },  
        { map = "6,-24", path = "right", gather = true, fight = false },  
        { map = "7,-24", path = "right", gather = true, fight = false },  
        { map = "8,-24", path = "right", gather = true, fight = false },  
        { map = "9,-24", path = "bottom", gather = true, fight = false },  
        { map = "9,-23", path = "left", gather = true, fight = false },  
        { map = "8,-23", path = "left", gather = true, fight = false },  
        { map = "7,-23", path = "left", gather = true, fight = false },  
        { map = "6,-23", path = "left", gather = true, fight = false },  
        { map = "5,-23", path = "left", gather = false, fight = false },  
        { map = "4,-23", path = "left", gather = true, fight = false },  
        { map = "3,-23", path = "left", gather = true, fight = false },  
        { map = "2,-23", path = "bottom", gather = true, fight = false },  
        { map = "2,-22", path = "right", gather = true, fight = false },  
        { map = "3,-22", path = "right", gather = true, fight = false },  
        { map = "4,-22", path = "right", gather = true, fight = false },  
        { map = "5,-22", path = "right", gather = true, fight = false },  
        { map = "6,-22", path = "right", gather = true, fight = false },  
        { map = "7,-22", path = "bottom", gather = true, fight = false },  
        { map = "7,-21", path = "bottom", gather = true, fight = false },  
        { map = "7,-20", path = "left", gather = true, fight = false },  
        { map = "6,-20", path = "top", gather = false, fight = false },  
        { map = "6,-21", path = "left", gather = true, fight = false },  
        { map = "5,-21", path = "left", gather = true, fight = false },  
        { map = "4,-21", path = "bottom", gather = true, fight = false },  
        { map = "4,-20", path = "bottom", gather = true, fight = false },  
        { map = "191104002", path = "left", gather = false, fight = false },  
        { map = "192415750", path = "409" },  
        { map = "4,-19", path = "bottom", gather = false, fight = false },  
    }

    return Path:new(path, "GatherAllAstrubNorthEast", true)
end

function GatherPathManager:GatherAllAstrubNorthWest()
    local path = {
        { map = "191104002", path = "right", gather = false, fight = false },  
        { map = "192415750", path = "409" },  
        {map = "5,-19", path = "left", gather = false, fight = false},
        { map = "5,-18", path = "right", gather = false, fight = false },  
        { map = "6,-18", path = "right", gather = true, fight = false },  
        { map = "7,-18", path = "top", gather = true, fight = false },  
        { map = "7,-19", path = "top", gather = false, fight = false },  
        { map = "7,-20", path = "top", gather = true, fight = false },  
        { map = "7,-21", path = "top", gather = true, fight = false },  
        { map = "7,-22", path = "top", gather = true, fight = false },  
        { map = "7,-23", path = "top", gather = true, fight = false },  
        { map = "7,-24", path = "right", gather = true, fight = false },  
        { map = "8,-24", path = "right", gather = true, fight = false },  
        { map = "9,-24", path = "top", gather = true, fight = false },  
        { map = "9,-25", path = "right", gather = false, fight = false },  
        { map = "10,-25", path = "top", gather = false, fight = false },  
        { map = "10,-26", path = "left", gather = true, fight = false },  
        { map = "9,-26", path = "top", gather = false, fight = false },  
        { map = "9,-27", path = "left", gather = true, fight = false },  
        { map = "8,-27", path = "top", gather = true, fight = false },  
        { map = "8,-28", path = "top", gather = true, fight = false },  
        { map = "8,-29", path = "right", gather = true, fight = false },  
        { map = "9,-29", path = "right", gather = true, fight = false },  
        { map = "10,-29", path = "bottom", gather = true, fight = false },  
        { map = "10,-28", path = "right", gather = true, fight = false },  
        { map = "11,-28", path = "right", gather = true, fight = false },  
        { map = "12,-28", path = "right", gather = true, fight = false },  
        { map = "13,-28", path = "bottom", gather = true, fight = false },  
        { map = "13,-27", path = "left", gather = true, fight = false },  
        { map = "12,-27", path = "bottom", gather = true, fight = false },  
        { map = "12,-26", path = "bottom", gather = true, fight = false },  
        { map = "12,-25", path = "bottom", gather = true, fight = false },  
        { map = "12,-24", path = "bottom", gather = true, fight = false },  
        { map = "12,-23", path = "bottom", gather = true, fight = false },  
        { map = "12,-22", path = "left", gather = true, fight = false },  
        { map = "11,-22", path = "bottom", gather = false, fight = false },  
        { map = "11,-21", path = "bottom", gather = false, fight = false },  
        { map = "11,-20", path = "bottom", gather = false, fight = false },  
        { map = "11,-19", path = "bottom", gather = false, fight = false },  
        { map = "11,-18", path = "bottom", gather = false, fight = false },  
        { map = "11,-17", path = "bottom", gather = false, fight = false },  
        { map = "11,-16", path = "left", gather = false, fight = false },  
        { map = "10,-16", path = "left", gather = false, fight = false },  
        { map = "9,-16", path = "left", gather = false, fight = false },  
        { map = "8,-16", path = "left", gather = false, fight = false },  
        { map = "7,-16", path = "bottom", gather = true, fight = false },  
        { map = "7,-15", path = "left", gather = true, fight = false },  
        { map = "6,-15", path = "top", gather = true, fight = false },  
        { map = "6,-16", path = "left", gather = true, fight = false },  
        { map = "5,-15", path = "left", gather = true, fight = false },  
        { map = "4,-16", path = "left", gather = true, fight = false },  
        { map = "3,-15", path = "left", gather = true, fight = false },  
        { map = "5,-16", path = "bottom", gather = true, fight = false },  
        { map = "3,-16", path = "bottom", gather = true, fight = false },  
        { map = "4,-15", path = "top", gather = true, fight = false },  
        { map = "2,-15", path = "top", gather = true, fight = false },  
        { map = "2,-16", path = "top", gather = true, fight = false },  
        { map = "2,-17", path = "top", gather = true, fight = false },  
        { map = "2,-18", path = "right", gather = true, fight = false },  
        { map = "3,-18", path = "top", gather = true, fight = false },  
        { map = "3,-19", path = "right", gather = true, fight = false },  
        { map = "4,-19", path = "bottom", gather = false, fight = false },  
    }

    return Path:new(path, "GatherAllAstrubNorthWest", true)
end

function GatherPathManager:GatherAllAstrubSouth()
    local path = {
        { map = "191104002", path = "right", gather = false, fight = false },  
        { map = "192415750", path = "409" },          
        {map = "5,-19", path = "left", gather = false, fight = false},
        { map = "5,-18", path = "bottom", gather = false, fight = false },  
        { map = "5,-17", path = "bottom", gather = false, fight = false },  
        { map = "5,-16", path = "bottom", gather = true, fight = false },  
        { map = "5,-15", path = "left", gather = true, fight = false },  
        { map = "4,-15", path = "left", gather = true, fight = false },  
        { map = "3,-15", path = "left", gather = true, fight = false },  
        { map = "3,-14", path = "right", gather = true, fight = false },  
        { map = "4,-14", path = "right", gather = true, fight = false },  
        { map = "5,-14", path = "right", gather = true, fight = false },  
        { map = "6,-14", path = "right", gather = true, fight = false },  
        { map = "7,-14", path = "right", gather = true, fight = false },  
        { map = "8,-14", path = "right", gather = true, fight = false },  
        { map = "9,-14", path = "right", gather = true, fight = false },  
        { map = "10,-14", path = "right", gather = true, fight = false },  
        { map = "11,-14", path = "bottom", gather = true, fight = false },  
        { map = "11,-13", path = "left", gather = true, fight = false },  
        { map = "10,-13", path = "left", gather = true, fight = false },  
        { map = "9,-13", path = "left", gather = true, fight = false },  
        { map = "8,-13", path = "left", gather = true, fight = false },  
        { map = "7,-13", path = "left", gather = true, fight = false },  
        { map = "6,-13", path = "left", gather = true, fight = false },  
        { map = "5,-13", path = "left", gather = true, fight = false },  
        { map = "4,-13", path = "left", gather = true, fight = false },  
        { map = "3,-13", path = "bottom", gather = true, fight = false },  
        { map = "3,-12", path = "right", gather = true, fight = false },  
        { map = "4,-12", path = "right", gather = true, fight = false },  
        { map = "5,-12", path = "right", gather = true, fight = false },  
        { map = "6,-12", path = "right", gather = true, fight = false },  
        { map = "7,-12", path = "right", gather = true, fight = false },  
        { map = "8,-12", path = "right", gather = true, fight = false },  
        { map = "9,-12", path = "right", gather = true, fight = false },  
        { map = "10,-12", path = "right", gather = true, fight = false },  
        { map = "11,-12", path = "bottom", gather = true, fight = false },  
        { map = "11,-11", path = "left", gather = true, fight = false },  
        { map = "10,-11", path = "left|bottom", gather = true, fight = false },  
        { map = "10,-10", path = "left", gather = true, fight = false },  
        { map = "9,-11", path = "bottom", gather = true, fight = false },  
        { map = "9,-10", path = "bottom", gather = true, fight = false },  
        { map = "9,-9", path = "bottom", gather = true, fight = false },  
        { map = "9,-8", path = "left", gather = true, fight = false },  
        { map = "8,-8", path = "top", gather = true, fight = false },  
        { map = "8,-9", path = "top", gather = true, fight = false },  
        { map = "8,-10", path = "top", gather = true, fight = false },  
        { map = "8,-11", path = "left", gather = true, fight = false },  
        { map = "7,-11", path = "left", gather = true, fight = false },  
        { map = "6,-11", path = "left", gather = true, fight = false },  
        { map = "5,-11", path = "left", gather = true, fight = false },  
        { map = "4,-11", path = "left", gather = true, fight = false },  
        { map = "2,-15", path = "bottom", gather = true, fight = false },  
        { map = "2,-14", path = "right", gather = true, fight = false },  
        { map = "1,-15", path = "top", gather = true, fight = false },  
        { map = "1,-14", path = "top", gather = true, fight = false },  
        { map = "1,-13", path = "top", gather = false, fight = false },  
        { map = "2,-13", path = "left", gather = true, fight = false },  
        { map = "2,-12", path = "top", gather = false, fight = false },  
        { map = "2,-11", path = "top", gather = true, fight = false },  
        { map = "3,-11", path = "bottom", gather = true, fight = false },  
        { map = "3,-10", path = "right", gather = true, fight = false },  
        { map = "4,-10", path = "right", gather = true, fight = false },  
        { map = "5,-10", path = "right", gather = true, fight = false },  
        { map = "6,-10", path = "right", gather = true, fight = false },  
        { map = "7,-10", path = "bottom", gather = true, fight = false },  
        { map = "7,-9", path = "left", gather = true, fight = false },  
        { map = "6,-9", path = "left", gather = true, fight = false },  
        { map = "5,-9", path = "left", gather = true, fight = false },  
        { map = "4,-9", path = "left", gather = true, fight = false },  
        { map = "3,-9", path = "left", gather = true, fight = false },  
        { map = "2,-9", path = "top", gather = true, fight = false },  
        { map = "2,-10", path = "right", gather = true, fight = false },  
        { map = "1,-16", path = "top", gather = true, fight = false },  
        { map = "1,-17", path = "top", gather = true, fight = false },  
        { map = "1,-18", path = "right", gather = true, fight = false },  
        { map = "2,-18", path = "right", gather = true, fight = false },  
        { map = "3,-18", path = "top", gather = true, fight = false },  
        { map = "3,-19", path = "right", gather = true, fight = false },  
        { map = "4,-19", path = "bottom", gather = false, fight = false },  
    }

    return Path:new(path, "GatherAllAstrubSouth", true)
end

function GatherPathManager:GetRandomAstrubGatherAllPath()
    local rand = math.random(1, 3)

    if (rand == 1) then
        return self:GatherAllAstrubNorthEast()
    elseif (rand == 2) then
        return self:GatherAllAstrubNorthWest()
    elseif (rand == 3) then
        return self:GatherAllAstrubSouth()
    end
end

function GatherPathManager:GatherBoisAstrub()
	local path = {
        {map = "5,-18", path = "top"}, --map zaap astrub
        {map = "5,-19", path = "left"}, --map zaap astrub
		{map = "-2,-20", path = "right"},
		{map = "4,-21", path = "bottom", gather = true},
		{map = "4,-20", path = "bottom", gather = true},
		{map = "6,-21", path = "left", gather = true},
		{map = "5,-21", path = "left", gather = true},
		{map = "6,-20", path = "top"},
		{map = "4,-19", path = "left"},
		{map = "3,-19", path = "bottom", gather = true},
		{map = "3,-18", path = "bottom"},
		{map = "3,-17", path = "right"},
		{map = "17,-21", path = "right"},
		{map = "4,-17", path = "right", gather = true},
		{map = "5,-17", path = "bottom", gather = true},
		{map = "5,-16", path = "right", gather = true},
		{map = "6,-16", path = "bottom"},
		{map = "6,-15", path = "right", gather = true},
		{map = "7,-15", path = "right", gather = true},
		{map = "8,-15", path = "bottom"},
		{map = "8,-14", path = "right", gather = true},
		{map = "9,-14", path = "right", gather = true},
		{map = "10,-14", path = "bottom", gather = true},
		{map = "10,-13", path = "bottom", gather = true},
		{map = "10,-12", path = "bottom"},
		{map = "10,-11", path = "bottom"},
		{map = "10,-10", path = "left", gather = true},
		{map = "9,-11", path = "left", gather = true},
		{map = "9,-10", path = "top"},
		{map = "8,-11", path = "top", gather = true},
		{map = "8,-12", path = "top", gather = true},
		{map = "8,-13", path = "left"},
		{map = "7,-13", path = "left", gather = true},
		{map = "6,-13", path = "bottom", gather = true},
		{map = "6,-12", path = "bottom", gather = true},
		{map = "6,-11", path = "left", gather = true},
		{map = "5,-11", path = "top"},
		{map = "5,-12", path = "top", gather = true},
		{map = "5,-13", path = "left", gather = true},
		{map = "4,-10", path = "left", gather = true},
		{map = "4,-13", path = "bottom", gather = true},
		{map = "4,-12", path = "bottom", gather = true},
		{map = "4,-11", path = "bottom", gather = true},
		{map = "3,-10", path = "top", gather = true},
		{map = "2,-11", path = "top", gather = true},
		{map = "3,-11", path = "left", gather = true},
		{map = "2,-12", path = "top"},
		{map = "2,-13", path = "top"},
		{map = "2,-14", path = "top", gather = true},
		{map = "2,-15", path = "right", gather = true},
		{map = "4,-15", path = "top", gather = true},
		{map = "3,-15", path = "right", gather = true},
		{map = "4,-16", path = "left"},
		{map = "3,-16", path = "left"},
		{map = "2,-16", path = "top", gather = true},
		{map = "2,-17", path = "left", gather = true},
		{map = "1,-17", path = "bottom"},
		{map = "1,-16", path = "bottom", gather = true},
		{map = "1,-15", path = "bottom"},
		{map = "1,-14", path = "left", gather = true},
		{map = "0,-14", path = "top"},
		{map = "0,-15", path = "left", gather = true},
		{map = "-1,-15", path = "left", gather = true},
		{map = "-2,-15", path = "left", gather = true},
		{map = "0,-17", path = "left", gather = true},
		{map = "-1,-17", path = "left", gather = true},
		{map = "-2,-17", path = "left", gather = true},
		{map = "-3,-17", path = "top", gather = true},
		{map = "-3,-15", path = "top", gather = true},
		{map = "-3,-16", path = "right", gather = true},
		{map = "-2,-16", path = "right", gather = true},
		{map = "-1,-16", path = "right", gather = true},
		{map = "-2,-18", path = "right", gather = true},
		{map = "-3,-18", path = "right", gather = true},
		{map = "-1,-18", path = "right", gather = true},
		{map = "0,-18", path = "right", gather = true},
		{map = "0,-16", path = "top", gather = true},
		{map = "1,-18", path = "top", gather = true},
		{map = "1,-19", path = "left", gather = true},
		{map = "0,-19", path = "left", gather = true},
		{map = "-1,-19", path = "left", gather = true},
		{map = "-2,-19", path = "left", gather = true},
		{map = "-3,-19", path = "top", gather = true},
		{map = "-3,-20", path = "right", gather = true},
		{map = "-1,-20", path = "right", gather = true},
		{map = "0,-20", path = "right", gather = true},
		{map = "1,-20", path = "right", gather = true},
		{map = "2,-20", path = "top", gather = true},
		{map = "2,-21", path = "left", gather = true},
		{map = "1,-21", path = "left"},
		{map = "0,-21", path = "left", gather = true},
		{map = "-1,-21", path = "left", gather = true},
		{map = "-2,-21", path = "left", gather = true},
		{map = "-3,-21", path = "top", gather = true},
		{map = "-3,-22", path = "right", gather = true},
		{map = "-2,-22", path = "right", gather = true},
		{map = "-1,-22", path = "right", gather = true},
		{map = "1,-22", path = "right", gather = true},
		{map = "2,-22", path = "top", gather = true},
		{map = "0,-22", path = "right", gather = true},
		{map = "2,-23", path = "left", gather = true},
		{map = "1,-23", path = "left", gather = true},
		{map = "0,-23", path = "left", gather = true},
		{map = "-1,-23", path = "left", gather = true},
		{map = "-2,-23", path = "top", gather = true},
		{map = "-2,-24", path = "right", gather = true},
		{map = "-1,-24", path = "right", gather = true},
		{map = "0,-24", path = "right", gather = true},
		{map = "1,-24", path = "right", gather = true},
		{map = "2,-24", path = "top", gather = true},
		{map = "2,-25", path = "left", gather = true},
		{map = "1,-25", path = "left", gather = true},
		{map = "0,-25", path = "left", gather = true},
		{map = "-1,-25", path = "left", gather = true},
		{map = "-2,-25", path = "top", gather = true},
		{map = "-2,-26", path = "right", gather = true},
		{map = "-1,-26", path = "right", gather = true},
		{map = "0,-26", path = "right", gather = true},
		{map = "1,-26", path = "right", gather = true},
		{map = "2,-26", path = "top", gather = true},
		{map = "1,-27", path = "left", gather = true},
		{map = "2,-27", path = "left", gather = true},
		{map = "0,-27", path = "left", gather = true},
		{map = "-1,-27", path = "left", gather = true},
		{map = "-2,-27", path = "top", gather = true},
		{map = "-2,-28", path = "right", gather = true},
		{map = "-1,-28", path = "right", gather = true},
		{map = "1,-28", path = "right", gather = true},
		{map = "0,-28", path = "right", gather = true},
		{map = "2,-28", path = "top", gather = true},
		{map = "2,-29", path = "top", gather = true},
		{map = "2,-30", path = "right", gather = true},
		{map = "3,-30", path = "bottom"},
		{map = "3,-29", path = "bottom"},
		{map = "3,-28", path = "bottom"},
		{map = "3,-27", path = "bottom"},
		{map = "3,-25", path = "bottom"},
		{map = "3,-26", path = "bottom"},
		{map = "3,-24", path = "bottom"},
		{map = "3,-23", path = "bottom"},
		{map = "3,-22", path = "right"},
		{map = "4,-22", path = "right"},
		{map = "5,-22", path = "bottom"},
	}

    return Path:new(path, "GatherBoisAstrub", true)
end

function GatherPathManager:DeplacementsCereale()
    local path = {
        { map = "192937992", path = "424"}, -- map interieur atelier paysan vers porte
        { map = "4,-19", path = "top", gather = false, fight = false },  
        { map = "4,-20", path = "top", gather = false, fight = false },  
        { map = "191104002", path = "top", gather = false, fight = false },  
        { map = "192415750", path = "409" },  
        { map = "4,-17", path = "top", gather = false, fight = false },  
        { map = "3,-19", path = "right", gather = false, fight = false },  
        { map = "3,-18", path = "right", gather = false, fight = false },  
        { map = "3,-17", path = "right", gather = false, fight = false },  
        { map = "2,-18", path = "right", gather = false, fight = false },  
        { map = "1,-18", path = "right", gather = false, fight = false },  
        { map = "0,-18", path = "right", gather = false, fight = false },  
        { map = "-1,-18", path = "right", gather = false, fight = false },  
        { map = "-2,-18", path = "right", gather = false, fight = false },  
        { map = "-3,-18", path = "right", gather = false, fight = false },  
        { map = "2,-17", path = "top", gather = false, fight = false },  
        { map = "2,-16", path = "top", gather = false, fight = false },  
        { map = "1,-16", path = "top", gather = false, fight = false },  
        { map = "1,-17", path = "top", gather = false, fight = false },  
        { map = "0,-17", path = "top", gather = false, fight = false },  
        { map = "-1,-17", path = "top", gather = false, fight = false },  
        { map = "-2,-17", path = "top", gather = false, fight = false },  
        { map = "-3,-17", path = "top", gather = false, fight = false },  
        { map = "-3,-16", path = "top", gather = false, fight = false },  
        { map = "-2,-16", path = "top", gather = false, fight = false },  
        { map = "-1,-16", path = "top", gather = false, fight = false },  
        { map = "0,-16", path = "top", gather = false, fight = false },  
        { map = "-3,-15", path = "top", gather = false, fight = false },  
        { map = "-3,-14", path = "top", gather = false, fight = false },  
        { map = "-2,-14", path = "top", gather = false, fight = false },  
        { map = "-2,-15", path = "top", gather = false, fight = false },  
        { map = "-1,-15", path = "top", gather = false, fight = false },  
        { map = "-1,-14", path = "top", gather = false, fight = false },  
        { map = "0,-14", path = "top", gather = false, fight = false },  
        { map = "0,-15", path = "top", gather = false, fight = false },  
        { map = "1,-15", path = "top", gather = false, fight = false },  
        { map = "1,-14", path = "top", gather = false, fight = false },  
        { map = "2,-15", path = "top", gather = false, fight = false },  
        { map = "2,-14", path = "top", gather = false, fight = false },  
        { map = "4,-14", path = "top", gather = false, fight = false },  
        { map = "3,-14", path = "top", gather = false, fight = false },  
        { map = "4,-16", path = "right", gather = false, fight = false },  
        { map = "3,-16", path = "right", gather = false, fight = false },  
        { map = "5,-17", path = "top", gather = false, fight = false },  
        { map = "5,-16", path = "top", gather = false, fight = false },  
        { map = "5,-14", path = "top", gather = false, fight = false },  
        { map = "5,-18", path = "top", gather = false, fight = false },  
        { map = "5,-19", path = "left", gather = false, fight = false },  
        { map = "6,-19", path = "left", gather = false, fight = false },  
        { map = "6,-18", path = "left", gather = false, fight = false },  
        { map = "6,-17", path = "left", gather = false, fight = false },  
        { map = "6,-16", path = "left", gather = false, fight = false },  
        { map = "6,-15", path = "left", gather = false, fight = false },  
        { map = "7,-16", path = "left", gather = false, fight = false },  
        { map = "7,-15", path = "left", gather = false, fight = false },  
        { map = "7,-14", path = "left", gather = false, fight = false },  
        { map = "6,-14", path = "left", gather = false, fight = false },  
        { map = "-3,-13", path = "top", gather = false, fight = false },  
        { map = "-2,-13", path = "top", gather = false, fight = false },  
        { map = "-1,-13", path = "top", gather = false, fight = false },  
        { map = "1,-13", path = "top", gather = false, fight = false },  
        { map = "0,-13", path = "top", gather = false, fight = false },  
        { map = "2,-13", path = "top", gather = false, fight = false },  
        { map = "3,-13", path = "top", gather = false, fight = false },  
        { map = "3,-12", path = "top", gather = false, fight = false },  
        { map = "3,-10", path = "top", gather = false, fight = false },  
        { map = "3,-9", path = "top", gather = false, fight = false },  
        { map = "3,-8", path = "top", gather = false, fight = false },  
        { map = "4,-8", path = "top", gather = false, fight = false },  
        { map = "4,-9", path = "top", gather = false, fight = false },  
        { map = "5,-9", path = "top", gather = false, fight = false },  
        { map = "6,-9", path = "top", gather = false, fight = false },  
        { map = "7,-9", path = "top", gather = false, fight = false },  
        { map = "7,-8", path = "top", gather = false, fight = false },  
        { map = "8,-8", path = "top", gather = false, fight = false },  
        { map = "8,-9", path = "top", gather = false, fight = false },  
        { map = "9,-9", path = "top", gather = false, fight = false },  
        { map = "9,-8", path = "top", gather = false, fight = false },  
        { map = "9,-10", path = "top", gather = false, fight = false },  
        { map = "10,-10", path = "top", gather = false, fight = false },  
        { map = "10,-11", path = "top", gather = false, fight = false },  
        { map = "10,-12", path = "top", gather = false, fight = false },  
        { map = "11,-11", path = "left", gather = false, fight = false },  
        { map = "11,-12", path = "left", gather = false, fight = false },  
        { map = "11,-13", path = "left", gather = false, fight = false },  
        { map = "11,-14", path = "left", gather = false, fight = false },  
        { map = "10,-14", path = "left", gather = false, fight = false },  
        { map = "9,-14", path = "left", gather = false, fight = false },  
        { map = "10,-13", path = "left", gather = false, fight = false },  
        { map = "9,-13", path = "left", gather = false, fight = false },  
        { map = "8,-14", path = "left", gather = false, fight = false },  
        { map = "8,-13", path = "left", gather = false, fight = false },  
        { map = "7,-13", path = "left", gather = false, fight = false },  
        { map = "9,-12", path = "left", gather = false, fight = false },  
        { map = "9,-11", path = "left", gather = false, fight = false },  
        { map = "8,-11", path = "left", gather = false, fight = false },  
        { map = "8,-10", path = "left", gather = false, fight = false },  
        { map = "7,-12", path = "left", gather = false, fight = false },  
        { map = "8,-12", path = "left", gather = false, fight = false },  
        { map = "7,-11", path = "left", gather = false, fight = false },  
        { map = "7,-10", path = "left", gather = false, fight = false },  
        { map = "6,-13", path = "left", gather = false, fight = false },  
        { map = "6,-12", path = "left", gather = false, fight = false },  
        { map = "6,-11", path = "left", gather = false, fight = false },  
        { map = "6,-10", path = "left", gather = false, fight = false },  
        { map = "5,-13", path = "top", gather = false, fight = false },  
        { map = "5,-12", path = "top", gather = false, fight = false },  
        { map = "5,-11", path = "top", gather = false, fight = false },  
        { map = "5,-10", path = "top", gather = false, fight = false },  
        { map = "4,-10", path = "top", gather = false, fight = false },  
        { map = "4,-11", path = "top", gather = false, fight = false },  
        { map = "4,-12", path = "top", gather = false, fight = false },  
        { map = "3,-11", path = "top", gather = false, fight = false },  
        { map = "4,-13", path = "top", gather = false, fight = false },  
        { map = "7,-17", path = "top", gather = false, fight = false },  
        { map = "8,-17", path = "top", gather = false, fight = false },  
        { map = "8,-16", path = "top", gather = false, fight = false },  
        { map = "8,-15", path = "top", gather = false, fight = false },  
        { map = "9,-17", path = "top", gather = false, fight = false },  
        { map = "9,-16", path = "top", gather = false, fight = false },  
        { map = "9,-15", path = "top", gather = false, fight = false },  
        { map = "10,-15", path = "top", gather = false, fight = false },  
        { map = "10,-16", path = "top", gather = false, fight = false },  
        { map = "10,-17", path = "top", gather = false, fight = false },  
        { map = "11,-17", path = "top", gather = false, fight = false },  
        { map = "11,-16", path = "top", gather = false, fight = false },  
        { map = "11,-15", path = "top", gather = false, fight = false },  
        { map = "12,-18", path = "left", gather = false, fight = false },  
        { map = "12,-17", path = "left", gather = false, fight = false },  
        { map = "12,-15", path = "left", gather = false, fight = false },  
        { map = "12,-16", path = "left", gather = false, fight = false },  
        { map = "11,-18", path = "left", gather = false, fight = false },  
        { map = "10,-18", path = "left", gather = false, fight = false },  
        { map = "9,-18", path = "left", gather = false, fight = false },  
        { map = "8,-18", path = "left", gather = false, fight = false },  
        { map = "7,-18", path = "left", gather = false, fight = false },  
        { map = "7,-19", path = "bottom", gather = false, fight = false },  
        { map = "8,-19", path = "bottom", gather = false, fight = false },  
        { map = "11,-19", path = "top", gather = false, fight = false },  
        { map = "12,-19", path = "top", gather = false, fight = false },  
        { map = "12,-20", path = "left", gather = false, fight = false },  
        { map = "11,-20", path = "left", gather = false, fight = false },  
        { map = "10,-20", path = "left", gather = false, fight = false },  
        { map = "9,-20", path = "left", gather = false, fight = false },  
        { map = "8,-20", path = "left", gather = false, fight = false },  
        { map = "7,-20", path = "left", gather = false, fight = false },  
        { map = "6,-20", path = "left", gather = false, fight = false },  
        { map = "5,-20", path = "left", gather = false, fight = false },  
        { map = "3,-20", path = "right", gather = false, fight = false },  
        { map = "2,-20", path = "right", gather = false, fight = false },  
        { map = "2,-19", path = "right", gather = false, fight = false },  
        { map = "1,-20", path = "right", gather = false, fight = false },  
        { map = "1,-19", path = "right", gather = false, fight = false },  
        { map = "0,-20", path = "right", gather = false, fight = false },  
        { map = "0,-19", path = "right", gather = false, fight = false },  
        { map = "-1,-20", path = "right", gather = false, fight = false },  
        { map = "-1,-19", path = "right", gather = false, fight = false },  
        { map = "-2,-20", path = "right", gather = false, fight = false },  
        { map = "-2,-19", path = "right", gather = false, fight = false },  
        { map = "-3,-20", path = "right", gather = false, fight = false },  
        { map = "-3,-19", path = "right", gather = false, fight = false },  
        { map = "1,-21", path = "right", gather = false, fight = false },  
        { map = "0,-21", path = "right", gather = false, fight = false },  
        { map = "-1,-21", path = "right", gather = false, fight = false },  
        { map = "1,-27", path = "right", gather = false, fight = false },  
        { map = "0,-27", path = "right", gather = false, fight = false },  
        { map = "-1,-27", path = "right", gather = false, fight = false },  
        { map = "-2,-27", path = "right", gather = false, fight = false },  
        { map = "-3,-27", path = "right", gather = false, fight = false },  
        { map = "-3,-26", path = "right", gather = false, fight = false },  
        { map = "-3,-25", path = "right", gather = false, fight = false },  
        { map = "-3,-24", path = "right", gather = false, fight = false },  
        { map = "-3,-23", path = "right", gather = false, fight = false },  
        { map = "-3,-22", path = "right", gather = false, fight = false },  
        { map = "-3,-21", path = "right", gather = false, fight = false },  
        { map = "-2,-21", path = "right", gather = false, fight = false },  
        { map = "-2,-22", path = "right", gather = false, fight = false },  
        { map = "-1,-22", path = "right", gather = false, fight = false },  
        { map = "0,-22", path = "right", gather = false, fight = false },  
        { map = "1,-22", path = "right", gather = false, fight = false },  
        { map = "1,-23", path = "right", gather = false, fight = false },  
        { map = "0,-23", path = "right", gather = false, fight = false },  
        { map = "-1,-23", path = "right", gather = false, fight = false },  
        { map = "-2,-23", path = "right", gather = false, fight = false },  
        { map = "-2,-24", path = "right", gather = false, fight = false },  
        { map = "-1,-24", path = "right", gather = false, fight = false },  
        { map = "0,-24", path = "right", gather = false, fight = false },  
        { map = "1,-24", path = "right", gather = false, fight = false },  
        { map = "1,-25", path = "right", gather = false, fight = false },  
        { map = "0,-25", path = "right", gather = false, fight = false },  
        { map = "-1,-25", path = "right", gather = false, fight = false },  
        { map = "-2,-25", path = "right", gather = false, fight = false },  
        { map = "-2,-26", path = "right", gather = false, fight = false },  
        { map = "-1,-26", path = "right", gather = false, fight = false },  
        { map = "0,-26", path = "right", gather = false, fight = false },  
        { map = "1,-26", path = "right", gather = false, fight = false },  
        { map = "-3,-28", path = "bottom", gather = false, fight = false },  
        { map = "-2,-28", path = "bottom", gather = false, fight = false },  
        { map = "-3,-29", path = "bottom", gather = false, fight = false },  
        { map = "-2,-29", path = "bottom", gather = false, fight = false },  
        { map = "-1,-28", path = "bottom", gather = false, fight = false },  
        { map = "0,-28", path = "bottom", gather = false, fight = false },  
        { map = "1,-28", path = "bottom", gather = false, fight = false },  
        { map = "2,-28", path = "bottom", gather = false, fight = false },  
        { map = "2,-29", path = "bottom", gather = false, fight = false },  
        { map = "9,-21", path = "left", gather = false, fight = false },  
        { map = "10,-21", path = "left", gather = false, fight = false },  
        { map = "11,-21", path = "left", gather = false, fight = false },  
        { map = "12,-21", path = "left", gather = false, fight = false },  
        { map = "4,-21", path = "right", gather = false, fight = false },  
        { map = "5,-21", path = "right", gather = false, fight = false },  
        { map = "6,-21", path = "right", gather = true, fight = false },  
        { map = "7,-21", path = "top", gather = true, fight = false },  
        { map = "7,-22", path = "left", gather = true, fight = false },  
        { map = "6,-22", path = "left", gather = true, fight = false },  
        { map = "5,-22", path = "left", gather = true, fight = false },  
        { map = "4,-22", path = "left", gather = true, fight = false },  
        { map = "3,-22", path = "top", gather = true, fight = false },  
        { map = "3,-23", path = "right", gather = true, fight = false },  
        { map = "4,-23", path = "right", gather = true, fight = false },  
        { map = "5,-23", path = "right", gather = true, fight = false },  
        { map = "6,-23", path = "right", gather = true, fight = false },  
        { map = "7,-23", path = "right", gather = true, fight = false },  
        { map = "8,-23", path = "right", gather = true, fight = false },  
        { map = "9,-23", path = "top", gather = true, fight = false },  
        { map = "9,-24", path = "left", gather = true, fight = false },  
        { map = "8,-24", path = "left", gather = true, fight = false },  
        { map = "189794311", path = "left", gather = true, fight = false },  --mapid exterieur atelier paysan
        { map = "6,-24", path = "left", gather = true, fight = false },  
        { map = "5,-24", path = "left", gather = true, fight = false },  
        { map = "4,-24", path = "left", gather = true, fight = false },  
        { map = "3,-24", path = "top", gather = true, fight = false },  
        { map = "7,-25", path = "top", gather = true, fight = false },  
        { map = "3,-26", path = "top", gather = true, fight = false },  
        { map = "7,-27", path = "top", gather = true, fight = false },  
        { map = "7,-28", path = "left", gather = true, fight = false },  
        { map = "7,-26", path = "left", gather = true, fight = false },  
        { map = "6,-26", path = "left", gather = true, fight = false },  
        { map = "5,-26", path = "left", gather = true, fight = false },  
        { map = "4,-26", path = "left", gather = true, fight = false },  
        { map = "6,-28", path = "left", gather = true, fight = false },  
        { map = "5,-28", path = "left", gather = true, fight = false },  
        { map = "4,-28", path = "left", gather = true, fight = false },  
        { map = "4,-27", path = "right", gather = true, fight = false },  
        { map = "3,-27", path = "right", gather = true, fight = false },  
        { map = "5,-27", path = "right", gather = true, fight = false },  
        { map = "6,-27", path = "right", gather = true, fight = false },  
        { map = "6,-25", path = "right", gather = true, fight = false },  
        { map = "5,-25", path = "right", gather = true, fight = false },  
        { map = "4,-25", path = "right", gather = true, fight = false },  
        { map = "3,-25", path = "right", gather = true, fight = false },  
        { map = "3,-28", path = "top", gather = true, fight = false },  
        { map = "3,-29", path = "right", gather = true, fight = false },  
        { map = "4,-29", path = "right", gather = true, fight = false },  
        { map = "5,-29", path = "right", gather = true, fight = false },  
        { map = "6,-29", path = "top", gather = true, fight = false },  
        { map = "6,-30", path = "left", gather = true, fight = false },  
        { map = "5,-30", path = "left", gather = true, fight = false },  
        { map = "4,-30", path = "top", gather = true, fight = false },  
        { map = "4,-31", path = "left", gather = true, fight = false },  
        { map = "3,-31", path = "bottom", gather = true, fight = false },  
        { map = "3,-30", path = "left", gather = true, fight = false },  
        { map = "2,-27", path = "bottom", gather = false, fight = false },  
        { map = "2,-26", path = "bottom", gather = false, fight = false },  
        { map = "2,-25", path = "bottom", gather = false, fight = false },  
        { map = "2,-24", path = "bottom", gather = false, fight = false },  
        { map = "2,-23", path = "bottom", gather = false, fight = false },  
        { map = "2,-22", path = "bottom", gather = false, fight = false },  
        { map = "2,-21", path = "right", gather = false, fight = false },  
        { map = "3,-21", path = "right", gather = false, fight = false },  
        { map = "8,-21", path = "left", gather = false, fight = false },  
        { map = "8,-22", path = "left", gather = false, fight = false },  
        { map = "9,-22", path = "left", gather = false, fight = false },  
        { map = "11,-22", path = "bottom", gather = false, fight = false },  
        { map = "11,-23", path = "bottom", gather = false, fight = false },  
        { map = "11,-24", path = "bottom", gather = false, fight = false },  
        { map = "11,-25", path = "bottom", gather = false, fight = false },  
        { map = "11,-26", path = "bottom", gather = false, fight = false },  
        { map = "11,-27", path = "bottom", gather = false, fight = false },  
        { map = "11,-28", path = "bottom", gather = false, fight = false },  
        { map = "12,-28", path = "left", gather = false, fight = false },  
        { map = "13,-28", path = "left", gather = false, fight = false },  
        { map = "13,-27", path = "left", gather = false, fight = false },  
        { map = "12,-27", path = "left", gather = false, fight = false },  
        { map = "12,-26", path = "left", gather = false, fight = false },  
        { map = "12,-25", path = "left", gather = false, fight = false },  
        { map = "12,-24", path = "left", gather = false, fight = false },  
        { map = "12,-23", path = "left", gather = false, fight = false },  
        { map = "12,-22", path = "left", gather = false, fight = false },  
        { map = "10,-22", path = "right", gather = false, fight = false },  
        { map = "10,-23", path = "right", gather = false, fight = false },  
        { map = "10,-24", path = "right", gather = false, fight = false },  
        { map = "10,-25", path = "right", gather = false, fight = false },  
        { map = "10,-26", path = "right", gather = false, fight = false },  
        { map = "10,-27", path = "right", gather = false, fight = false },  
        { map = "10,-28", path = "right", gather = false, fight = false },  
        { map = "10,-29", path = "left", gather = false, fight = false },  
        { map = "9,-29", path = "left", gather = false, fight = false },  
        { map = "8,-29", path = "bottom", gather = false, fight = false },  
        { map = "9,-28", path = "left", gather = false, fight = false },  
        { map = "8,-28", path = "left", gather = false, fight = false },  
        { map = "8,-27", path = "top", gather = false, fight = false },  
        { map = "9,-27", path = "top", gather = false, fight = false },  
        { map = "9,-26", path = "top", gather = false, fight = false },  
        { map = "8,-26", path = "top", gather = false, fight = false },  
        { map = "8,-25", path = "top", gather = false, fight = false },  
        { map = "9,-25", path = "bottom", gather = false, fight = false },  
        { map = "2,-30", path = "bottom", gather = false, fight = false },  
    }

    return Path:new(path, "GatherCereale", true)
end

